#
#  Do not edit this file.  This file is generated from 
#  package.bld.  Any modifications to this file will be 
#  overwritten whenever makefiles are re-generated.
#

unexport MAKEFILE_LIST
MK_NOGENDEPS := $(filter clean,$(MAKECMDGOALS))
override PKGDIR = ti/sdo/fc/utils
XDCINCS = -I. -I$(strip $(subst ;, -I,$(subst $(space),\$(space),$(XPKGPATH))))
XDCCFGDIR = package/cfg/

#
# The following dependencies ensure package.mak is rebuilt
# in the event that some included BOM script changes.
#
ifneq (clean,$(MAKECMDGOALS))
/swcoe/sdk/cm/netra/ti-ezsdk_dm816x-evm_5_05_01_04/component-sources/xdctools_3_23_03_53/include/utils.tci:
package.mak: /swcoe/sdk/cm/netra/ti-ezsdk_dm816x-evm_5_05_01_04/component-sources/xdctools_3_23_03_53/include/utils.tci
/swcoe/sdk/cm/netra/ti-ezsdk_dm816x-evm_5_05_01_04/component-sources/xdctools_3_23_03_53/packages/xdc/xdc.tci:
package.mak: /swcoe/sdk/cm/netra/ti-ezsdk_dm816x-evm_5_05_01_04/component-sources/xdctools_3_23_03_53/packages/xdc/xdc.tci
/swcoe/sdk/cm/netra/ti-ezsdk_dm816x-evm_5_05_01_04/component-sources/xdctools_3_23_03_53/packages/xdc/template.xs:
package.mak: /swcoe/sdk/cm/netra/ti-ezsdk_dm816x-evm_5_05_01_04/component-sources/xdctools_3_23_03_53/packages/xdc/template.xs
/swcoe/sdk/cm/netra/ti-ezsdk_dm816x-evm_5_05_01_04/component-sources/xdctools_3_23_03_53/packages/xdc/om2.xs:
package.mak: /swcoe/sdk/cm/netra/ti-ezsdk_dm816x-evm_5_05_01_04/component-sources/xdctools_3_23_03_53/packages/xdc/om2.xs
/swcoe/sdk/cm/netra/ti-ezsdk_dm816x-evm_5_05_01_04/component-sources/xdctools_3_23_03_53/packages/xdc/xmlgen.xs:
package.mak: /swcoe/sdk/cm/netra/ti-ezsdk_dm816x-evm_5_05_01_04/component-sources/xdctools_3_23_03_53/packages/xdc/xmlgen.xs
/swcoe/sdk/cm/netra/ti-ezsdk_dm816x-evm_5_05_01_04/component-sources/xdctools_3_23_03_53/packages/xdc/xmlgen2.xs:
package.mak: /swcoe/sdk/cm/netra/ti-ezsdk_dm816x-evm_5_05_01_04/component-sources/xdctools_3_23_03_53/packages/xdc/xmlgen2.xs
/swcoe/sdk/cm/netra/ti-ezsdk_dm816x-evm_5_05_01_04/component-sources/xdctools_3_23_03_53/packages/xdc/IPackage.xs:
package.mak: /swcoe/sdk/cm/netra/ti-ezsdk_dm816x-evm_5_05_01_04/component-sources/xdctools_3_23_03_53/packages/xdc/IPackage.xs
/swcoe/sdk/cm/netra/ti-ezsdk_dm816x-evm_5_05_01_04/component-sources/xdctools_3_23_03_53/packages/xdc/package.xs:
package.mak: /swcoe/sdk/cm/netra/ti-ezsdk_dm816x-evm_5_05_01_04/component-sources/xdctools_3_23_03_53/packages/xdc/package.xs
/swcoe/sdk/cm/netra/ti-ezsdk_dm816x-evm_5_05_01_04/component-sources/xdctools_3_23_03_53/packages/xdc/services/global/Clock.xs:
package.mak: /swcoe/sdk/cm/netra/ti-ezsdk_dm816x-evm_5_05_01_04/component-sources/xdctools_3_23_03_53/packages/xdc/services/global/Clock.xs
/swcoe/sdk/cm/netra/ti-ezsdk_dm816x-evm_5_05_01_04/component-sources/xdctools_3_23_03_53/packages/xdc/services/global/Trace.xs:
package.mak: /swcoe/sdk/cm/netra/ti-ezsdk_dm816x-evm_5_05_01_04/component-sources/xdctools_3_23_03_53/packages/xdc/services/global/Trace.xs
/swcoe/sdk/cm/netra/ti-ezsdk_dm816x-evm_5_05_01_04/component-sources/xdctools_3_23_03_53/packages/xdc/bld/bld.js:
package.mak: /swcoe/sdk/cm/netra/ti-ezsdk_dm816x-evm_5_05_01_04/component-sources/xdctools_3_23_03_53/packages/xdc/bld/bld.js
/swcoe/sdk/cm/netra/ti-ezsdk_dm816x-evm_5_05_01_04/component-sources/xdctools_3_23_03_53/packages/xdc/bld/BuildEnvironment.xs:
package.mak: /swcoe/sdk/cm/netra/ti-ezsdk_dm816x-evm_5_05_01_04/component-sources/xdctools_3_23_03_53/packages/xdc/bld/BuildEnvironment.xs
/swcoe/sdk/cm/netra/ti-ezsdk_dm816x-evm_5_05_01_04/component-sources/xdctools_3_23_03_53/packages/xdc/bld/PackageContents.xs:
package.mak: /swcoe/sdk/cm/netra/ti-ezsdk_dm816x-evm_5_05_01_04/component-sources/xdctools_3_23_03_53/packages/xdc/bld/PackageContents.xs
/swcoe/sdk/cm/netra/ti-ezsdk_dm816x-evm_5_05_01_04/component-sources/xdctools_3_23_03_53/packages/xdc/bld/_gen.xs:
package.mak: /swcoe/sdk/cm/netra/ti-ezsdk_dm816x-evm_5_05_01_04/component-sources/xdctools_3_23_03_53/packages/xdc/bld/_gen.xs
/swcoe/sdk/cm/netra/ti-ezsdk_dm816x-evm_5_05_01_04/component-sources/xdctools_3_23_03_53/packages/xdc/bld/Library.xs:
package.mak: /swcoe/sdk/cm/netra/ti-ezsdk_dm816x-evm_5_05_01_04/component-sources/xdctools_3_23_03_53/packages/xdc/bld/Library.xs
/swcoe/sdk/cm/netra/ti-ezsdk_dm816x-evm_5_05_01_04/component-sources/xdctools_3_23_03_53/packages/xdc/bld/Executable.xs:
package.mak: /swcoe/sdk/cm/netra/ti-ezsdk_dm816x-evm_5_05_01_04/component-sources/xdctools_3_23_03_53/packages/xdc/bld/Executable.xs
/swcoe/sdk/cm/netra/ti-ezsdk_dm816x-evm_5_05_01_04/component-sources/xdctools_3_23_03_53/packages/xdc/bld/Repository.xs:
package.mak: /swcoe/sdk/cm/netra/ti-ezsdk_dm816x-evm_5_05_01_04/component-sources/xdctools_3_23_03_53/packages/xdc/bld/Repository.xs
/swcoe/sdk/cm/netra/ti-ezsdk_dm816x-evm_5_05_01_04/component-sources/xdctools_3_23_03_53/packages/xdc/bld/Configuration.xs:
package.mak: /swcoe/sdk/cm/netra/ti-ezsdk_dm816x-evm_5_05_01_04/component-sources/xdctools_3_23_03_53/packages/xdc/bld/Configuration.xs
/swcoe/sdk/cm/netra/ti-ezsdk_dm816x-evm_5_05_01_04/component-sources/xdctools_3_23_03_53/packages/xdc/bld/Script.xs:
package.mak: /swcoe/sdk/cm/netra/ti-ezsdk_dm816x-evm_5_05_01_04/component-sources/xdctools_3_23_03_53/packages/xdc/bld/Script.xs
/swcoe/sdk/cm/netra/ti-ezsdk_dm816x-evm_5_05_01_04/component-sources/xdctools_3_23_03_53/packages/xdc/bld/Manifest.xs:
package.mak: /swcoe/sdk/cm/netra/ti-ezsdk_dm816x-evm_5_05_01_04/component-sources/xdctools_3_23_03_53/packages/xdc/bld/Manifest.xs
/swcoe/sdk/cm/netra/ti-ezsdk_dm816x-evm_5_05_01_04/component-sources/xdctools_3_23_03_53/packages/xdc/bld/Utils.xs:
package.mak: /swcoe/sdk/cm/netra/ti-ezsdk_dm816x-evm_5_05_01_04/component-sources/xdctools_3_23_03_53/packages/xdc/bld/Utils.xs
/swcoe/sdk/cm/netra/ti-ezsdk_dm816x-evm_5_05_01_04/component-sources/xdctools_3_23_03_53/packages/xdc/bld/ITarget.xs:
package.mak: /swcoe/sdk/cm/netra/ti-ezsdk_dm816x-evm_5_05_01_04/component-sources/xdctools_3_23_03_53/packages/xdc/bld/ITarget.xs
/swcoe/sdk/cm/netra/ti-ezsdk_dm816x-evm_5_05_01_04/component-sources/xdctools_3_23_03_53/packages/xdc/bld/ITarget2.xs:
package.mak: /swcoe/sdk/cm/netra/ti-ezsdk_dm816x-evm_5_05_01_04/component-sources/xdctools_3_23_03_53/packages/xdc/bld/ITarget2.xs
/swcoe/sdk/cm/netra/ti-ezsdk_dm816x-evm_5_05_01_04/component-sources/xdctools_3_23_03_53/packages/xdc/bld/ITargetFilter.xs:
package.mak: /swcoe/sdk/cm/netra/ti-ezsdk_dm816x-evm_5_05_01_04/component-sources/xdctools_3_23_03_53/packages/xdc/bld/ITargetFilter.xs
/swcoe/sdk/cm/netra/ti-ezsdk_dm816x-evm_5_05_01_04/component-sources/xdctools_3_23_03_53/packages/xdc/bld/package.xs:
package.mak: /swcoe/sdk/cm/netra/ti-ezsdk_dm816x-evm_5_05_01_04/component-sources/xdctools_3_23_03_53/packages/xdc/bld/package.xs
/swcoe/sdk/cm/netra/ti-ezsdk_dm816x-evm_5_05_01_04/component-sources/framework_components_3_22_01_07/framework_components.bld:
package.mak: /swcoe/sdk/cm/netra/ti-ezsdk_dm816x-evm_5_05_01_04/component-sources/framework_components_3_22_01_07/framework_components.bld
/swcoe/sdk/cm/netra/ti-ezsdk_dm816x-evm_5_05_01_04/component-sources/xdctools_3_23_03_53/packages/ti/targets/ITarget.xs:
package.mak: /swcoe/sdk/cm/netra/ti-ezsdk_dm816x-evm_5_05_01_04/component-sources/xdctools_3_23_03_53/packages/ti/targets/ITarget.xs
/swcoe/sdk/cm/netra/ti-ezsdk_dm816x-evm_5_05_01_04/component-sources/xdctools_3_23_03_53/packages/ti/targets/C28_large.xs:
package.mak: /swcoe/sdk/cm/netra/ti-ezsdk_dm816x-evm_5_05_01_04/component-sources/xdctools_3_23_03_53/packages/ti/targets/C28_large.xs
/swcoe/sdk/cm/netra/ti-ezsdk_dm816x-evm_5_05_01_04/component-sources/xdctools_3_23_03_53/packages/ti/targets/C28_float.xs:
package.mak: /swcoe/sdk/cm/netra/ti-ezsdk_dm816x-evm_5_05_01_04/component-sources/xdctools_3_23_03_53/packages/ti/targets/C28_float.xs
/swcoe/sdk/cm/netra/ti-ezsdk_dm816x-evm_5_05_01_04/component-sources/xdctools_3_23_03_53/packages/ti/targets/package.xs:
package.mak: /swcoe/sdk/cm/netra/ti-ezsdk_dm816x-evm_5_05_01_04/component-sources/xdctools_3_23_03_53/packages/ti/targets/package.xs
/swcoe/sdk/cm/netra/ti-ezsdk_dm816x-evm_5_05_01_04/component-sources/xdctools_3_23_03_53/packages/ti/targets/arm/IArm.xs:
package.mak: /swcoe/sdk/cm/netra/ti-ezsdk_dm816x-evm_5_05_01_04/component-sources/xdctools_3_23_03_53/packages/ti/targets/arm/IArm.xs
/swcoe/sdk/cm/netra/ti-ezsdk_dm816x-evm_5_05_01_04/component-sources/xdctools_3_23_03_53/packages/ti/targets/arm/package.xs:
package.mak: /swcoe/sdk/cm/netra/ti-ezsdk_dm816x-evm_5_05_01_04/component-sources/xdctools_3_23_03_53/packages/ti/targets/arm/package.xs
/swcoe/sdk/cm/netra/ti-ezsdk_dm816x-evm_5_05_01_04/component-sources/xdctools_3_23_03_53/packages/ti/targets/arm/elf/IArm.xs:
package.mak: /swcoe/sdk/cm/netra/ti-ezsdk_dm816x-evm_5_05_01_04/component-sources/xdctools_3_23_03_53/packages/ti/targets/arm/elf/IArm.xs
/swcoe/sdk/cm/netra/ti-ezsdk_dm816x-evm_5_05_01_04/component-sources/xdctools_3_23_03_53/packages/ti/targets/arm/elf/package.xs:
package.mak: /swcoe/sdk/cm/netra/ti-ezsdk_dm816x-evm_5_05_01_04/component-sources/xdctools_3_23_03_53/packages/ti/targets/arm/elf/package.xs
/swcoe/sdk/cm/netra/ti-ezsdk_dm816x-evm_5_05_01_04/component-sources/xdctools_3_23_03_53/packages/ti/targets/elf/ITarget.xs:
package.mak: /swcoe/sdk/cm/netra/ti-ezsdk_dm816x-evm_5_05_01_04/component-sources/xdctools_3_23_03_53/packages/ti/targets/elf/ITarget.xs
/swcoe/sdk/cm/netra/ti-ezsdk_dm816x-evm_5_05_01_04/component-sources/xdctools_3_23_03_53/packages/ti/targets/elf/TMS470.xs:
package.mak: /swcoe/sdk/cm/netra/ti-ezsdk_dm816x-evm_5_05_01_04/component-sources/xdctools_3_23_03_53/packages/ti/targets/elf/TMS470.xs
/swcoe/sdk/cm/netra/ti-ezsdk_dm816x-evm_5_05_01_04/component-sources/xdctools_3_23_03_53/packages/ti/targets/elf/package.xs:
package.mak: /swcoe/sdk/cm/netra/ti-ezsdk_dm816x-evm_5_05_01_04/component-sources/xdctools_3_23_03_53/packages/ti/targets/elf/package.xs
/swcoe/sdk/cm/netra/ti-ezsdk_dm816x-evm_5_05_01_04/component-sources/xdctools_3_23_03_53/packages/gnu/targets/ITarget.xs:
package.mak: /swcoe/sdk/cm/netra/ti-ezsdk_dm816x-evm_5_05_01_04/component-sources/xdctools_3_23_03_53/packages/gnu/targets/ITarget.xs
/swcoe/sdk/cm/netra/ti-ezsdk_dm816x-evm_5_05_01_04/component-sources/xdctools_3_23_03_53/packages/gnu/targets/Linux86.xs:
package.mak: /swcoe/sdk/cm/netra/ti-ezsdk_dm816x-evm_5_05_01_04/component-sources/xdctools_3_23_03_53/packages/gnu/targets/Linux86.xs
/swcoe/sdk/cm/netra/ti-ezsdk_dm816x-evm_5_05_01_04/component-sources/xdctools_3_23_03_53/packages/gnu/targets/Mingw.xs:
package.mak: /swcoe/sdk/cm/netra/ti-ezsdk_dm816x-evm_5_05_01_04/component-sources/xdctools_3_23_03_53/packages/gnu/targets/Mingw.xs
/swcoe/sdk/cm/netra/ti-ezsdk_dm816x-evm_5_05_01_04/component-sources/xdctools_3_23_03_53/packages/gnu/targets/MVArm9.xs:
package.mak: /swcoe/sdk/cm/netra/ti-ezsdk_dm816x-evm_5_05_01_04/component-sources/xdctools_3_23_03_53/packages/gnu/targets/MVArm9.xs
/swcoe/sdk/cm/netra/ti-ezsdk_dm816x-evm_5_05_01_04/component-sources/xdctools_3_23_03_53/packages/gnu/targets/UCArm9.xs:
package.mak: /swcoe/sdk/cm/netra/ti-ezsdk_dm816x-evm_5_05_01_04/component-sources/xdctools_3_23_03_53/packages/gnu/targets/UCArm9.xs
/swcoe/sdk/cm/netra/ti-ezsdk_dm816x-evm_5_05_01_04/component-sources/xdctools_3_23_03_53/packages/gnu/targets/package.xs:
package.mak: /swcoe/sdk/cm/netra/ti-ezsdk_dm816x-evm_5_05_01_04/component-sources/xdctools_3_23_03_53/packages/gnu/targets/package.xs
/swcoe/sdk/cm/netra/ti-ezsdk_dm816x-evm_5_05_01_04/component-sources/xdctools_3_23_03_53/packages/gnu/targets/arm/GCArmv6.xs:
package.mak: /swcoe/sdk/cm/netra/ti-ezsdk_dm816x-evm_5_05_01_04/component-sources/xdctools_3_23_03_53/packages/gnu/targets/arm/GCArmv6.xs
/swcoe/sdk/cm/netra/ti-ezsdk_dm816x-evm_5_05_01_04/component-sources/xdctools_3_23_03_53/packages/gnu/targets/arm/GCArmv7A.xs:
package.mak: /swcoe/sdk/cm/netra/ti-ezsdk_dm816x-evm_5_05_01_04/component-sources/xdctools_3_23_03_53/packages/gnu/targets/arm/GCArmv7A.xs
/swcoe/sdk/cm/netra/ti-ezsdk_dm816x-evm_5_05_01_04/component-sources/xdctools_3_23_03_53/packages/gnu/targets/arm/M3.xs:
package.mak: /swcoe/sdk/cm/netra/ti-ezsdk_dm816x-evm_5_05_01_04/component-sources/xdctools_3_23_03_53/packages/gnu/targets/arm/M3.xs
/swcoe/sdk/cm/netra/ti-ezsdk_dm816x-evm_5_05_01_04/component-sources/xdctools_3_23_03_53/packages/gnu/targets/arm/M4.xs:
package.mak: /swcoe/sdk/cm/netra/ti-ezsdk_dm816x-evm_5_05_01_04/component-sources/xdctools_3_23_03_53/packages/gnu/targets/arm/M4.xs
/swcoe/sdk/cm/netra/ti-ezsdk_dm816x-evm_5_05_01_04/component-sources/xdctools_3_23_03_53/packages/gnu/targets/arm/M4F.xs:
package.mak: /swcoe/sdk/cm/netra/ti-ezsdk_dm816x-evm_5_05_01_04/component-sources/xdctools_3_23_03_53/packages/gnu/targets/arm/M4F.xs
/swcoe/sdk/cm/netra/ti-ezsdk_dm816x-evm_5_05_01_04/component-sources/xdctools_3_23_03_53/packages/gnu/targets/arm/MVArm9.xs:
package.mak: /swcoe/sdk/cm/netra/ti-ezsdk_dm816x-evm_5_05_01_04/component-sources/xdctools_3_23_03_53/packages/gnu/targets/arm/MVArm9.xs
/swcoe/sdk/cm/netra/ti-ezsdk_dm816x-evm_5_05_01_04/component-sources/xdctools_3_23_03_53/packages/gnu/targets/arm/UCArm9.xs:
package.mak: /swcoe/sdk/cm/netra/ti-ezsdk_dm816x-evm_5_05_01_04/component-sources/xdctools_3_23_03_53/packages/gnu/targets/arm/UCArm9.xs
/swcoe/sdk/cm/netra/ti-ezsdk_dm816x-evm_5_05_01_04/component-sources/xdctools_3_23_03_53/packages/gnu/targets/arm/package.xs:
package.mak: /swcoe/sdk/cm/netra/ti-ezsdk_dm816x-evm_5_05_01_04/component-sources/xdctools_3_23_03_53/packages/gnu/targets/arm/package.xs
package.mak: package.bld
endif

ti.targets.arm.elf.M3.rootDir ?= /proj/productization/tools/cgt470/cgt470_4_9_2/
ti.targets.arm.elf.packageBase ?= /swcoe/sdk/cm/netra/ti-ezsdk_dm816x-evm_5_05_01_04/component-sources/xdctools_3_23_03_53/packages/ti/targets/arm/elf/
ti.targets.elf.C674.rootDir ?= /swcoe/sdk/cm/netra/ti-ezsdk_dm816x-evm_5_05_01_04/dsp-devkit/cgt6x_7_3_1
ti.targets.elf.packageBase ?= /swcoe/sdk/cm/netra/ti-ezsdk_dm816x-evm_5_05_01_04/component-sources/xdctools_3_23_03_53/packages/ti/targets/elf/
gnu.targets.arm.GCArmv5T.rootDir ?= /codesourcery/arm-2009q1/
gnu.targets.arm.packageBase ?= /swcoe/sdk/cm/netra/ti-ezsdk_dm816x-evm_5_05_01_04/component-sources/xdctools_3_23_03_53/packages/gnu/targets/arm/
.PRECIOUS: $(XDCCFGDIR)/%.oem3
.PHONY: all,em3 .dlls,em3 .executables,em3 test,em3
all,em3: .executables,em3
.executables,em3: .libraries,em3
.executables,em3: .dlls,em3
.dlls,em3: .libraries,em3
.libraries,em3: .interfaces
	@$(RM) $@
	@$(TOUCH) "$@"

.help::
	@$(ECHO) xdc test,em3
	@$(ECHO) xdc .executables,em3
	@$(ECHO) xdc .libraries,em3
	@$(ECHO) xdc .dlls,em3

.PRECIOUS: $(XDCCFGDIR)/%.oe674
.PHONY: all,e674 .dlls,e674 .executables,e674 test,e674
all,e674: .executables,e674
.executables,e674: .libraries,e674
.executables,e674: .dlls,e674
.dlls,e674: .libraries,e674
.libraries,e674: .interfaces
	@$(RM) $@
	@$(TOUCH) "$@"

.help::
	@$(ECHO) xdc test,e674
	@$(ECHO) xdc .executables,e674
	@$(ECHO) xdc .libraries,e674
	@$(ECHO) xdc .dlls,e674

.PRECIOUS: $(XDCCFGDIR)/%.ov5T
.PHONY: all,v5T .dlls,v5T .executables,v5T test,v5T
all,v5T: .executables,v5T
.executables,v5T: .libraries,v5T
.executables,v5T: .dlls,v5T
.dlls,v5T: .libraries,v5T
.libraries,v5T: .interfaces
	@$(RM) $@
	@$(TOUCH) "$@"

.help::
	@$(ECHO) xdc test,v5T
	@$(ECHO) xdc .executables,v5T
	@$(ECHO) xdc .libraries,v5T
	@$(ECHO) xdc .dlls,v5T


all: .executables 
.executables: .libraries .dlls
.libraries: .interfaces

PKGCFGS := $(wildcard package.xs) package/build.cfg
.interfaces: package/package.xdc.inc package/package.defs.h package.xdc $(PKGCFGS)

-include package/package.xdc.dep
package/%.xdc.inc package/%_ti.sdo.fc.utils.c package/%.defs.h: %.xdc $(PKGCFGS)
	@$(MSG) generating interfaces for package ti.sdo.fc.utils" (because $@ is older than $(firstword $?))" ...
	$(XSRUN) -f xdc/services/intern/cmd/build.xs $(MK_IDLOPTS) -m package/package.xdc.dep -i package/package.xdc.inc package.xdc

ifeq (,$(MK_NOGENDEPS))
-include package/package.cfg.dep
endif

package/package.ext.xml: package/package.cfg.xdc.inc
package/package.cfg.xdc.inc: $(XDCROOT)/packages/xdc/cfg/cfginc.js package.xdc
	@$(MSG) generating schema include file list ...
	$(CONFIG) -f $(XDCROOT)/packages/xdc/cfg/cfginc.js ti.sdo.fc.utils $@

.libraries,em3 .libraries: lib/debug/rmm.aem3

-include lib/debug/rmm.aem3.mak
lib/debug/rmm.aem3: 
	$(RM) $@
	@$(MSG) archiving package/lib/lib/debug/rmm/package/package_ti.sdo.fc.utils.oem3 package/lib/lib/debug/rmm/rmm.oem3  into $@ ...
	$(ti.targets.arm.elf.M3.rootDir)/bin/ar470  rq $@   package/lib/lib/debug/rmm/package/package_ti.sdo.fc.utils.oem3 package/lib/lib/debug/rmm/rmm.oem3 
lib/debug/rmm.aem3: export C_DIR=
lib/debug/rmm.aem3: PATH:=$(ti.targets.arm.elf.M3.rootDir)/bin/:$(PATH)

clean,em3 clean::
	-$(RM) lib/debug/rmm.aem3
.libraries,em3 .libraries: lib/release/rmm.aem3

-include lib/release/rmm.aem3.mak
lib/release/rmm.aem3: 
	$(RM) $@
	@$(MSG) archiving package/lib/lib/release/rmm/package/package_ti.sdo.fc.utils.oem3 package/lib/lib/release/rmm/rmm.oem3  into $@ ...
	$(ti.targets.arm.elf.M3.rootDir)/bin/ar470  rq $@   package/lib/lib/release/rmm/package/package_ti.sdo.fc.utils.oem3 package/lib/lib/release/rmm/rmm.oem3 
lib/release/rmm.aem3: export C_DIR=
lib/release/rmm.aem3: PATH:=$(ti.targets.arm.elf.M3.rootDir)/bin/:$(PATH)

clean,em3 clean::
	-$(RM) lib/release/rmm.aem3
.libraries,em3 .libraries: lib/debug/smgr.aem3

-include lib/debug/smgr.aem3.mak
lib/debug/smgr.aem3: 
	$(RM) $@
	@$(MSG) archiving package/lib/lib/debug/smgr/package/package_ti.sdo.fc.utils.oem3 package/lib/lib/debug/smgr/smgr.oem3  into $@ ...
	$(ti.targets.arm.elf.M3.rootDir)/bin/ar470  rq $@   package/lib/lib/debug/smgr/package/package_ti.sdo.fc.utils.oem3 package/lib/lib/debug/smgr/smgr.oem3 
lib/debug/smgr.aem3: export C_DIR=
lib/debug/smgr.aem3: PATH:=$(ti.targets.arm.elf.M3.rootDir)/bin/:$(PATH)

clean,em3 clean::
	-$(RM) lib/debug/smgr.aem3
.libraries,em3 .libraries: lib/release/smgr.aem3

-include lib/release/smgr.aem3.mak
lib/release/smgr.aem3: 
	$(RM) $@
	@$(MSG) archiving package/lib/lib/release/smgr/package/package_ti.sdo.fc.utils.oem3 package/lib/lib/release/smgr/smgr.oem3  into $@ ...
	$(ti.targets.arm.elf.M3.rootDir)/bin/ar470  rq $@   package/lib/lib/release/smgr/package/package_ti.sdo.fc.utils.oem3 package/lib/lib/release/smgr/smgr.oem3 
lib/release/smgr.aem3: export C_DIR=
lib/release/smgr.aem3: PATH:=$(ti.targets.arm.elf.M3.rootDir)/bin/:$(PATH)

clean,em3 clean::
	-$(RM) lib/release/smgr.aem3
.libraries,em3 .libraries: lib/debug/rmmp.aem3

-include lib/debug/rmmp.aem3.mak
lib/debug/rmmp.aem3: 
	$(RM) $@
	@$(MSG) archiving package/lib/lib/debug/rmmp/package/package_ti.sdo.fc.utils.oem3 package/lib/lib/debug/rmmp/rmmp.oem3 package/lib/lib/debug/rmmp/rmm.oem3  into $@ ...
	$(ti.targets.arm.elf.M3.rootDir)/bin/ar470  rq $@   package/lib/lib/debug/rmmp/package/package_ti.sdo.fc.utils.oem3 package/lib/lib/debug/rmmp/rmmp.oem3 package/lib/lib/debug/rmmp/rmm.oem3 
lib/debug/rmmp.aem3: export C_DIR=
lib/debug/rmmp.aem3: PATH:=$(ti.targets.arm.elf.M3.rootDir)/bin/:$(PATH)

clean,em3 clean::
	-$(RM) lib/debug/rmmp.aem3
.libraries,em3 .libraries: lib/release/rmmp.aem3

-include lib/release/rmmp.aem3.mak
lib/release/rmmp.aem3: 
	$(RM) $@
	@$(MSG) archiving package/lib/lib/release/rmmp/package/package_ti.sdo.fc.utils.oem3 package/lib/lib/release/rmmp/rmmp.oem3 package/lib/lib/release/rmmp/rmm.oem3  into $@ ...
	$(ti.targets.arm.elf.M3.rootDir)/bin/ar470  rq $@   package/lib/lib/release/rmmp/package/package_ti.sdo.fc.utils.oem3 package/lib/lib/release/rmmp/rmmp.oem3 package/lib/lib/release/rmmp/rmm.oem3 
lib/release/rmmp.aem3: export C_DIR=
lib/release/rmmp.aem3: PATH:=$(ti.targets.arm.elf.M3.rootDir)/bin/:$(PATH)

clean,em3 clean::
	-$(RM) lib/release/rmmp.aem3
.libraries,e674 .libraries: lib/debug/rmm.ae674

-include lib/debug/rmm.ae674.mak
lib/debug/rmm.ae674: 
	$(RM) $@
	@$(MSG) archiving package/lib/lib/debug/rmm/package/package_ti.sdo.fc.utils.oe674 package/lib/lib/debug/rmm/rmm.oe674  into $@ ...
	$(ti.targets.elf.C674.rootDir)/bin/ar6x  rq $@   package/lib/lib/debug/rmm/package/package_ti.sdo.fc.utils.oe674 package/lib/lib/debug/rmm/rmm.oe674 
lib/debug/rmm.ae674: export C_DIR=
lib/debug/rmm.ae674: PATH:=$(ti.targets.elf.C674.rootDir)/bin/:$(PATH)

clean,e674 clean::
	-$(RM) lib/debug/rmm.ae674
.libraries,e674 .libraries: lib/release/rmm.ae674

-include lib/release/rmm.ae674.mak
lib/release/rmm.ae674: 
	$(RM) $@
	@$(MSG) archiving package/lib/lib/release/rmm/package/package_ti.sdo.fc.utils.oe674 package/lib/lib/release/rmm/rmm.oe674  into $@ ...
	$(ti.targets.elf.C674.rootDir)/bin/ar6x  rq $@   package/lib/lib/release/rmm/package/package_ti.sdo.fc.utils.oe674 package/lib/lib/release/rmm/rmm.oe674 
lib/release/rmm.ae674: export C_DIR=
lib/release/rmm.ae674: PATH:=$(ti.targets.elf.C674.rootDir)/bin/:$(PATH)

clean,e674 clean::
	-$(RM) lib/release/rmm.ae674
.libraries,e674 .libraries: lib/debug/smgr.ae674

-include lib/debug/smgr.ae674.mak
lib/debug/smgr.ae674: 
	$(RM) $@
	@$(MSG) archiving package/lib/lib/debug/smgr/package/package_ti.sdo.fc.utils.oe674 package/lib/lib/debug/smgr/smgr.oe674  into $@ ...
	$(ti.targets.elf.C674.rootDir)/bin/ar6x  rq $@   package/lib/lib/debug/smgr/package/package_ti.sdo.fc.utils.oe674 package/lib/lib/debug/smgr/smgr.oe674 
lib/debug/smgr.ae674: export C_DIR=
lib/debug/smgr.ae674: PATH:=$(ti.targets.elf.C674.rootDir)/bin/:$(PATH)

clean,e674 clean::
	-$(RM) lib/debug/smgr.ae674
.libraries,e674 .libraries: lib/release/smgr.ae674

-include lib/release/smgr.ae674.mak
lib/release/smgr.ae674: 
	$(RM) $@
	@$(MSG) archiving package/lib/lib/release/smgr/package/package_ti.sdo.fc.utils.oe674 package/lib/lib/release/smgr/smgr.oe674  into $@ ...
	$(ti.targets.elf.C674.rootDir)/bin/ar6x  rq $@   package/lib/lib/release/smgr/package/package_ti.sdo.fc.utils.oe674 package/lib/lib/release/smgr/smgr.oe674 
lib/release/smgr.ae674: export C_DIR=
lib/release/smgr.ae674: PATH:=$(ti.targets.elf.C674.rootDir)/bin/:$(PATH)

clean,e674 clean::
	-$(RM) lib/release/smgr.ae674
.libraries,e674 .libraries: lib/debug/rmmp.ae674

-include lib/debug/rmmp.ae674.mak
lib/debug/rmmp.ae674: 
	$(RM) $@
	@$(MSG) archiving package/lib/lib/debug/rmmp/package/package_ti.sdo.fc.utils.oe674 package/lib/lib/debug/rmmp/rmmp.oe674 package/lib/lib/debug/rmmp/rmm.oe674  into $@ ...
	$(ti.targets.elf.C674.rootDir)/bin/ar6x  rq $@   package/lib/lib/debug/rmmp/package/package_ti.sdo.fc.utils.oe674 package/lib/lib/debug/rmmp/rmmp.oe674 package/lib/lib/debug/rmmp/rmm.oe674 
lib/debug/rmmp.ae674: export C_DIR=
lib/debug/rmmp.ae674: PATH:=$(ti.targets.elf.C674.rootDir)/bin/:$(PATH)

clean,e674 clean::
	-$(RM) lib/debug/rmmp.ae674
.libraries,e674 .libraries: lib/release/rmmp.ae674

-include lib/release/rmmp.ae674.mak
lib/release/rmmp.ae674: 
	$(RM) $@
	@$(MSG) archiving package/lib/lib/release/rmmp/package/package_ti.sdo.fc.utils.oe674 package/lib/lib/release/rmmp/rmmp.oe674 package/lib/lib/release/rmmp/rmm.oe674  into $@ ...
	$(ti.targets.elf.C674.rootDir)/bin/ar6x  rq $@   package/lib/lib/release/rmmp/package/package_ti.sdo.fc.utils.oe674 package/lib/lib/release/rmmp/rmmp.oe674 package/lib/lib/release/rmmp/rmm.oe674 
lib/release/rmmp.ae674: export C_DIR=
lib/release/rmmp.ae674: PATH:=$(ti.targets.elf.C674.rootDir)/bin/:$(PATH)

clean,e674 clean::
	-$(RM) lib/release/rmmp.ae674
.libraries,v5T .libraries: lib/debug/shmMp.av5T

-include lib/debug/shmMp.av5T.mak
lib/debug/shmMp.av5T: 
	$(RM) $@
	@$(MSG) archiving package/lib/lib/debug/shmMp/package/package_ti.sdo.fc.utils.ov5T package/lib/lib/debug/shmMp/shmmp.ov5T  into $@ ...
	$(gnu.targets.arm.GCArmv5T.rootDir)/arm-none-linux-gnueabi/bin/ar  cr $@   package/lib/lib/debug/shmMp/package/package_ti.sdo.fc.utils.ov5T package/lib/lib/debug/shmMp/shmmp.ov5T 
lib/debug/shmMp.av5T: export LD_LIBRARY_PATH=

clean,v5T clean::
	-$(RM) lib/debug/shmMp.av5T
.libraries,v5T .libraries: lib/release/shmMp.av5T

-include lib/release/shmMp.av5T.mak
lib/release/shmMp.av5T: 
	$(RM) $@
	@$(MSG) archiving package/lib/lib/release/shmMp/package/package_ti.sdo.fc.utils.ov5T package/lib/lib/release/shmMp/shmmp.ov5T  into $@ ...
	$(gnu.targets.arm.GCArmv5T.rootDir)/arm-none-linux-gnueabi/bin/ar  cr $@   package/lib/lib/release/shmMp/package/package_ti.sdo.fc.utils.ov5T package/lib/lib/release/shmMp/shmmp.ov5T 
lib/release/shmMp.av5T: export LD_LIBRARY_PATH=

clean,v5T clean::
	-$(RM) lib/release/shmMp.av5T
.libraries,v5T .libraries: lib/debug/rmm.av5T

-include lib/debug/rmm.av5T.mak
lib/debug/rmm.av5T: 
	$(RM) $@
	@$(MSG) archiving package/lib/lib/debug/rmm/package/package_ti.sdo.fc.utils.ov5T package/lib/lib/debug/rmm/rmm.ov5T package/lib/lib/debug/rmm/bios_rts.ov5T  into $@ ...
	$(gnu.targets.arm.GCArmv5T.rootDir)/arm-none-linux-gnueabi/bin/ar  cr $@   package/lib/lib/debug/rmm/package/package_ti.sdo.fc.utils.ov5T package/lib/lib/debug/rmm/rmm.ov5T package/lib/lib/debug/rmm/bios_rts.ov5T 
lib/debug/rmm.av5T: export LD_LIBRARY_PATH=

clean,v5T clean::
	-$(RM) lib/debug/rmm.av5T
.libraries,v5T .libraries: lib/release/rmm.av5T

-include lib/release/rmm.av5T.mak
lib/release/rmm.av5T: 
	$(RM) $@
	@$(MSG) archiving package/lib/lib/release/rmm/package/package_ti.sdo.fc.utils.ov5T package/lib/lib/release/rmm/rmm.ov5T package/lib/lib/release/rmm/bios_rts.ov5T  into $@ ...
	$(gnu.targets.arm.GCArmv5T.rootDir)/arm-none-linux-gnueabi/bin/ar  cr $@   package/lib/lib/release/rmm/package/package_ti.sdo.fc.utils.ov5T package/lib/lib/release/rmm/rmm.ov5T package/lib/lib/release/rmm/bios_rts.ov5T 
lib/release/rmm.av5T: export LD_LIBRARY_PATH=

clean,v5T clean::
	-$(RM) lib/release/rmm.av5T
.libraries,v5T .libraries: lib/debug/rmmp.av5T

-include lib/debug/rmmp.av5T.mak
lib/debug/rmmp.av5T: 
	$(RM) $@
	@$(MSG) archiving package/lib/lib/debug/rmmp/package/package_ti.sdo.fc.utils.ov5T package/lib/lib/debug/rmmp/rmmp.ov5T package/lib/lib/debug/rmmp/rmm.ov5T  into $@ ...
	$(gnu.targets.arm.GCArmv5T.rootDir)/arm-none-linux-gnueabi/bin/ar  cr $@   package/lib/lib/debug/rmmp/package/package_ti.sdo.fc.utils.ov5T package/lib/lib/debug/rmmp/rmmp.ov5T package/lib/lib/debug/rmmp/rmm.ov5T 
lib/debug/rmmp.av5T: export LD_LIBRARY_PATH=

clean,v5T clean::
	-$(RM) lib/debug/rmmp.av5T
.libraries,v5T .libraries: lib/release/rmmp.av5T

-include lib/release/rmmp.av5T.mak
lib/release/rmmp.av5T: 
	$(RM) $@
	@$(MSG) archiving package/lib/lib/release/rmmp/package/package_ti.sdo.fc.utils.ov5T package/lib/lib/release/rmmp/rmmp.ov5T package/lib/lib/release/rmmp/rmm.ov5T  into $@ ...
	$(gnu.targets.arm.GCArmv5T.rootDir)/arm-none-linux-gnueabi/bin/ar  cr $@   package/lib/lib/release/rmmp/package/package_ti.sdo.fc.utils.ov5T package/lib/lib/release/rmmp/rmmp.ov5T package/lib/lib/release/rmmp/rmm.ov5T 
lib/release/rmmp.av5T: export LD_LIBRARY_PATH=

clean,v5T clean::
	-$(RM) lib/release/rmmp.av5T
.libraries,v5T .libraries: lib/debug/smgrmp.av5T

-include lib/debug/smgrmp.av5T.mak
lib/debug/smgrmp.av5T: 
	$(RM) $@
	@$(MSG) archiving package/lib/lib/debug/smgrmp/package/package_ti.sdo.fc.utils.ov5T package/lib/lib/debug/smgrmp/smgrmp.ov5T package/lib/lib/debug/smgrmp/smgr.ov5T  into $@ ...
	$(gnu.targets.arm.GCArmv5T.rootDir)/arm-none-linux-gnueabi/bin/ar  cr $@   package/lib/lib/debug/smgrmp/package/package_ti.sdo.fc.utils.ov5T package/lib/lib/debug/smgrmp/smgrmp.ov5T package/lib/lib/debug/smgrmp/smgr.ov5T 
lib/debug/smgrmp.av5T: export LD_LIBRARY_PATH=

clean,v5T clean::
	-$(RM) lib/debug/smgrmp.av5T
.libraries,v5T .libraries: lib/release/smgrmp.av5T

-include lib/release/smgrmp.av5T.mak
lib/release/smgrmp.av5T: 
	$(RM) $@
	@$(MSG) archiving package/lib/lib/release/smgrmp/package/package_ti.sdo.fc.utils.ov5T package/lib/lib/release/smgrmp/smgrmp.ov5T package/lib/lib/release/smgrmp/smgr.ov5T  into $@ ...
	$(gnu.targets.arm.GCArmv5T.rootDir)/arm-none-linux-gnueabi/bin/ar  cr $@   package/lib/lib/release/smgrmp/package/package_ti.sdo.fc.utils.ov5T package/lib/lib/release/smgrmp/smgrmp.ov5T package/lib/lib/release/smgrmp/smgr.ov5T 
lib/release/smgrmp.av5T: export LD_LIBRARY_PATH=

clean,v5T clean::
	-$(RM) lib/release/smgrmp.av5T
.libraries,v5T .libraries: lib/debug/smgr.av5T

-include lib/debug/smgr.av5T.mak
lib/debug/smgr.av5T: 
	$(RM) $@
	@$(MSG) archiving package/lib/lib/debug/smgr/package/package_ti.sdo.fc.utils.ov5T package/lib/lib/debug/smgr/smgr.ov5T  into $@ ...
	$(gnu.targets.arm.GCArmv5T.rootDir)/arm-none-linux-gnueabi/bin/ar  cr $@   package/lib/lib/debug/smgr/package/package_ti.sdo.fc.utils.ov5T package/lib/lib/debug/smgr/smgr.ov5T 
lib/debug/smgr.av5T: export LD_LIBRARY_PATH=

clean,v5T clean::
	-$(RM) lib/debug/smgr.av5T
.libraries,v5T .libraries: lib/release/smgr.av5T

-include lib/release/smgr.av5T.mak
lib/release/smgr.av5T: 
	$(RM) $@
	@$(MSG) archiving package/lib/lib/release/smgr/package/package_ti.sdo.fc.utils.ov5T package/lib/lib/release/smgr/smgr.ov5T  into $@ ...
	$(gnu.targets.arm.GCArmv5T.rootDir)/arm-none-linux-gnueabi/bin/ar  cr $@   package/lib/lib/release/smgr/package/package_ti.sdo.fc.utils.ov5T package/lib/lib/release/smgr/smgr.ov5T 
lib/release/smgr.av5T: export LD_LIBRARY_PATH=

clean,v5T clean::
	-$(RM) lib/release/smgr.av5T
.libraries,v5T .libraries: lib/debug/shmNonMp.av5T

-include lib/debug/shmNonMp.av5T.mak
lib/debug/shmNonMp.av5T: 
	$(RM) $@
	@$(MSG) archiving package/lib/lib/debug/shmNonMp/package/package_ti.sdo.fc.utils.ov5T package/lib/lib/debug/shmNonMp/shm.ov5T  into $@ ...
	$(gnu.targets.arm.GCArmv5T.rootDir)/arm-none-linux-gnueabi/bin/ar  cr $@   package/lib/lib/debug/shmNonMp/package/package_ti.sdo.fc.utils.ov5T package/lib/lib/debug/shmNonMp/shm.ov5T 
lib/debug/shmNonMp.av5T: export LD_LIBRARY_PATH=

clean,v5T clean::
	-$(RM) lib/debug/shmNonMp.av5T
.libraries,v5T .libraries: lib/release/shmNonMp.av5T

-include lib/release/shmNonMp.av5T.mak
lib/release/shmNonMp.av5T: 
	$(RM) $@
	@$(MSG) archiving package/lib/lib/release/shmNonMp/package/package_ti.sdo.fc.utils.ov5T package/lib/lib/release/shmNonMp/shm.ov5T  into $@ ...
	$(gnu.targets.arm.GCArmv5T.rootDir)/arm-none-linux-gnueabi/bin/ar  cr $@   package/lib/lib/release/shmNonMp/package/package_ti.sdo.fc.utils.ov5T package/lib/lib/release/shmNonMp/shm.ov5T 
lib/release/shmNonMp.av5T: export LD_LIBRARY_PATH=

clean,v5T clean::
	-$(RM) lib/release/shmNonMp.av5T
test:;
%,copy:
	@$(if $<,,$(MSG) don\'t know how to build $*; exit 1)
	@$(MSG) cp $< $@
	$(RM) $@
	$(CP) $< $@
.PHONY: package_ti.sdo.fc.utils.oem3,copy
package_ti.sdo.fc.utils.oem3,copy : package_ti.sdo.fc.utils.oem3,0,copy package_ti.sdo.fc.utils.oem3,1,copy package_ti.sdo.fc.utils.oem3,2,copy package_ti.sdo.fc.utils.oem3,3,copy package_ti.sdo.fc.utils.oem3,4,copy package_ti.sdo.fc.utils.oem3,5,copy 
	@

package_ti.sdo.fc.utils.oem3,0,copy : package/lib/lib/debug/rmm/package/package_ti.sdo.fc.utils.oem3
package_ti.sdo.fc.utils.oem3,1,copy : package/lib/lib/debug/rmmp/package/package_ti.sdo.fc.utils.oem3
package_ti.sdo.fc.utils.oem3,2,copy : package/lib/lib/debug/smgr/package/package_ti.sdo.fc.utils.oem3
package_ti.sdo.fc.utils.oem3,3,copy : package/lib/lib/release/rmm/package/package_ti.sdo.fc.utils.oem3
package_ti.sdo.fc.utils.oem3,4,copy : package/lib/lib/release/rmmp/package/package_ti.sdo.fc.utils.oem3
package_ti.sdo.fc.utils.oem3,5,copy : package/lib/lib/release/smgr/package/package_ti.sdo.fc.utils.oem3
.PHONY: package_ti.sdo.fc.utils.sem3,copy
package_ti.sdo.fc.utils.sem3,copy : package_ti.sdo.fc.utils.sem3,0,copy package_ti.sdo.fc.utils.sem3,1,copy package_ti.sdo.fc.utils.sem3,2,copy package_ti.sdo.fc.utils.sem3,3,copy package_ti.sdo.fc.utils.sem3,4,copy package_ti.sdo.fc.utils.sem3,5,copy 
	@

package_ti.sdo.fc.utils.sem3,0,copy : package/lib/lib/debug/rmm/package/package_ti.sdo.fc.utils.sem3
package_ti.sdo.fc.utils.sem3,1,copy : package/lib/lib/debug/rmmp/package/package_ti.sdo.fc.utils.sem3
package_ti.sdo.fc.utils.sem3,2,copy : package/lib/lib/debug/smgr/package/package_ti.sdo.fc.utils.sem3
package_ti.sdo.fc.utils.sem3,3,copy : package/lib/lib/release/rmm/package/package_ti.sdo.fc.utils.sem3
package_ti.sdo.fc.utils.sem3,4,copy : package/lib/lib/release/rmmp/package/package_ti.sdo.fc.utils.sem3
package_ti.sdo.fc.utils.sem3,5,copy : package/lib/lib/release/smgr/package/package_ti.sdo.fc.utils.sem3
.PHONY: rmm.oem3,copy
rmm.oem3,copy : rmm.oem3,0,copy rmm.oem3,1,copy rmm.oem3,2,copy rmm.oem3,3,copy 
	@

rmm.oem3,0,copy : package/lib/lib/debug/rmm/rmm.oem3
rmm.oem3,1,copy : package/lib/lib/debug/rmmp/rmm.oem3
rmm.oem3,2,copy : package/lib/lib/release/rmm/rmm.oem3
rmm.oem3,3,copy : package/lib/lib/release/rmmp/rmm.oem3
.PHONY: rmm.sem3,copy
rmm.sem3,copy : rmm.sem3,0,copy rmm.sem3,1,copy rmm.sem3,2,copy rmm.sem3,3,copy 
	@

rmm.sem3,0,copy : package/lib/lib/debug/rmm/rmm.sem3
rmm.sem3,1,copy : package/lib/lib/debug/rmmp/rmm.sem3
rmm.sem3,2,copy : package/lib/lib/release/rmm/rmm.sem3
rmm.sem3,3,copy : package/lib/lib/release/rmmp/rmm.sem3
.PHONY: smgr.oem3,copy
smgr.oem3,copy : smgr.oem3,0,copy smgr.oem3,1,copy 
	@

smgr.oem3,0,copy : package/lib/lib/debug/smgr/smgr.oem3
smgr.oem3,1,copy : package/lib/lib/release/smgr/smgr.oem3
.PHONY: smgr.sem3,copy
smgr.sem3,copy : smgr.sem3,0,copy smgr.sem3,1,copy 
	@

smgr.sem3,0,copy : package/lib/lib/debug/smgr/smgr.sem3
smgr.sem3,1,copy : package/lib/lib/release/smgr/smgr.sem3
.PHONY: rmmp.oem3,copy
rmmp.oem3,copy : rmmp.oem3,0,copy rmmp.oem3,1,copy 
	@

rmmp.oem3,0,copy : package/lib/lib/debug/rmmp/rmmp.oem3
rmmp.oem3,1,copy : package/lib/lib/release/rmmp/rmmp.oem3
.PHONY: rmmp.sem3,copy
rmmp.sem3,copy : rmmp.sem3,0,copy rmmp.sem3,1,copy 
	@

rmmp.sem3,0,copy : package/lib/lib/debug/rmmp/rmmp.sem3
rmmp.sem3,1,copy : package/lib/lib/release/rmmp/rmmp.sem3
.PHONY: package_ti.sdo.fc.utils.oe674,copy
package_ti.sdo.fc.utils.oe674,copy : package_ti.sdo.fc.utils.oe674,0,copy package_ti.sdo.fc.utils.oe674,1,copy package_ti.sdo.fc.utils.oe674,2,copy package_ti.sdo.fc.utils.oe674,3,copy package_ti.sdo.fc.utils.oe674,4,copy package_ti.sdo.fc.utils.oe674,5,copy 
	@

package_ti.sdo.fc.utils.oe674,0,copy : package/lib/lib/debug/rmm/package/package_ti.sdo.fc.utils.oe674
package_ti.sdo.fc.utils.oe674,1,copy : package/lib/lib/debug/rmmp/package/package_ti.sdo.fc.utils.oe674
package_ti.sdo.fc.utils.oe674,2,copy : package/lib/lib/debug/smgr/package/package_ti.sdo.fc.utils.oe674
package_ti.sdo.fc.utils.oe674,3,copy : package/lib/lib/release/rmm/package/package_ti.sdo.fc.utils.oe674
package_ti.sdo.fc.utils.oe674,4,copy : package/lib/lib/release/rmmp/package/package_ti.sdo.fc.utils.oe674
package_ti.sdo.fc.utils.oe674,5,copy : package/lib/lib/release/smgr/package/package_ti.sdo.fc.utils.oe674
.PHONY: package_ti.sdo.fc.utils.se674,copy
package_ti.sdo.fc.utils.se674,copy : package_ti.sdo.fc.utils.se674,0,copy package_ti.sdo.fc.utils.se674,1,copy package_ti.sdo.fc.utils.se674,2,copy package_ti.sdo.fc.utils.se674,3,copy package_ti.sdo.fc.utils.se674,4,copy package_ti.sdo.fc.utils.se674,5,copy 
	@

package_ti.sdo.fc.utils.se674,0,copy : package/lib/lib/debug/rmm/package/package_ti.sdo.fc.utils.se674
package_ti.sdo.fc.utils.se674,1,copy : package/lib/lib/debug/rmmp/package/package_ti.sdo.fc.utils.se674
package_ti.sdo.fc.utils.se674,2,copy : package/lib/lib/debug/smgr/package/package_ti.sdo.fc.utils.se674
package_ti.sdo.fc.utils.se674,3,copy : package/lib/lib/release/rmm/package/package_ti.sdo.fc.utils.se674
package_ti.sdo.fc.utils.se674,4,copy : package/lib/lib/release/rmmp/package/package_ti.sdo.fc.utils.se674
package_ti.sdo.fc.utils.se674,5,copy : package/lib/lib/release/smgr/package/package_ti.sdo.fc.utils.se674
.PHONY: rmm.oe674,copy
rmm.oe674,copy : rmm.oe674,0,copy rmm.oe674,1,copy rmm.oe674,2,copy rmm.oe674,3,copy 
	@

rmm.oe674,0,copy : package/lib/lib/debug/rmm/rmm.oe674
rmm.oe674,1,copy : package/lib/lib/debug/rmmp/rmm.oe674
rmm.oe674,2,copy : package/lib/lib/release/rmm/rmm.oe674
rmm.oe674,3,copy : package/lib/lib/release/rmmp/rmm.oe674
.PHONY: rmm.se674,copy
rmm.se674,copy : rmm.se674,0,copy rmm.se674,1,copy rmm.se674,2,copy rmm.se674,3,copy 
	@

rmm.se674,0,copy : package/lib/lib/debug/rmm/rmm.se674
rmm.se674,1,copy : package/lib/lib/debug/rmmp/rmm.se674
rmm.se674,2,copy : package/lib/lib/release/rmm/rmm.se674
rmm.se674,3,copy : package/lib/lib/release/rmmp/rmm.se674
.PHONY: smgr.oe674,copy
smgr.oe674,copy : smgr.oe674,0,copy smgr.oe674,1,copy 
	@

smgr.oe674,0,copy : package/lib/lib/debug/smgr/smgr.oe674
smgr.oe674,1,copy : package/lib/lib/release/smgr/smgr.oe674
.PHONY: smgr.se674,copy
smgr.se674,copy : smgr.se674,0,copy smgr.se674,1,copy 
	@

smgr.se674,0,copy : package/lib/lib/debug/smgr/smgr.se674
smgr.se674,1,copy : package/lib/lib/release/smgr/smgr.se674
.PHONY: rmmp.oe674,copy
rmmp.oe674,copy : rmmp.oe674,0,copy rmmp.oe674,1,copy 
	@

rmmp.oe674,0,copy : package/lib/lib/debug/rmmp/rmmp.oe674
rmmp.oe674,1,copy : package/lib/lib/release/rmmp/rmmp.oe674
.PHONY: rmmp.se674,copy
rmmp.se674,copy : rmmp.se674,0,copy rmmp.se674,1,copy 
	@

rmmp.se674,0,copy : package/lib/lib/debug/rmmp/rmmp.se674
rmmp.se674,1,copy : package/lib/lib/release/rmmp/rmmp.se674
.PHONY: package_ti.sdo.fc.utils.ov5T,copy
package_ti.sdo.fc.utils.ov5T,copy : package_ti.sdo.fc.utils.ov5T,0,copy package_ti.sdo.fc.utils.ov5T,1,copy package_ti.sdo.fc.utils.ov5T,2,copy package_ti.sdo.fc.utils.ov5T,3,copy package_ti.sdo.fc.utils.ov5T,4,copy package_ti.sdo.fc.utils.ov5T,5,copy package_ti.sdo.fc.utils.ov5T,6,copy package_ti.sdo.fc.utils.ov5T,7,copy package_ti.sdo.fc.utils.ov5T,8,copy package_ti.sdo.fc.utils.ov5T,9,copy package_ti.sdo.fc.utils.ov5T,10,copy package_ti.sdo.fc.utils.ov5T,11,copy 
	@

package_ti.sdo.fc.utils.ov5T,0,copy : package/lib/lib/debug/rmm/package/package_ti.sdo.fc.utils.ov5T
package_ti.sdo.fc.utils.ov5T,1,copy : package/lib/lib/debug/rmmp/package/package_ti.sdo.fc.utils.ov5T
package_ti.sdo.fc.utils.ov5T,2,copy : package/lib/lib/debug/shmMp/package/package_ti.sdo.fc.utils.ov5T
package_ti.sdo.fc.utils.ov5T,3,copy : package/lib/lib/debug/shmNonMp/package/package_ti.sdo.fc.utils.ov5T
package_ti.sdo.fc.utils.ov5T,4,copy : package/lib/lib/debug/smgr/package/package_ti.sdo.fc.utils.ov5T
package_ti.sdo.fc.utils.ov5T,5,copy : package/lib/lib/debug/smgrmp/package/package_ti.sdo.fc.utils.ov5T
package_ti.sdo.fc.utils.ov5T,6,copy : package/lib/lib/release/rmm/package/package_ti.sdo.fc.utils.ov5T
package_ti.sdo.fc.utils.ov5T,7,copy : package/lib/lib/release/rmmp/package/package_ti.sdo.fc.utils.ov5T
package_ti.sdo.fc.utils.ov5T,8,copy : package/lib/lib/release/shmMp/package/package_ti.sdo.fc.utils.ov5T
package_ti.sdo.fc.utils.ov5T,9,copy : package/lib/lib/release/shmNonMp/package/package_ti.sdo.fc.utils.ov5T
package_ti.sdo.fc.utils.ov5T,10,copy : package/lib/lib/release/smgr/package/package_ti.sdo.fc.utils.ov5T
package_ti.sdo.fc.utils.ov5T,11,copy : package/lib/lib/release/smgrmp/package/package_ti.sdo.fc.utils.ov5T
.PHONY: package_ti.sdo.fc.utils.sv5T,copy
package_ti.sdo.fc.utils.sv5T,copy : package_ti.sdo.fc.utils.sv5T,0,copy package_ti.sdo.fc.utils.sv5T,1,copy package_ti.sdo.fc.utils.sv5T,2,copy package_ti.sdo.fc.utils.sv5T,3,copy package_ti.sdo.fc.utils.sv5T,4,copy package_ti.sdo.fc.utils.sv5T,5,copy package_ti.sdo.fc.utils.sv5T,6,copy package_ti.sdo.fc.utils.sv5T,7,copy package_ti.sdo.fc.utils.sv5T,8,copy package_ti.sdo.fc.utils.sv5T,9,copy package_ti.sdo.fc.utils.sv5T,10,copy package_ti.sdo.fc.utils.sv5T,11,copy 
	@

package_ti.sdo.fc.utils.sv5T,0,copy : package/lib/lib/debug/rmm/package/package_ti.sdo.fc.utils.sv5T
package_ti.sdo.fc.utils.sv5T,1,copy : package/lib/lib/debug/rmmp/package/package_ti.sdo.fc.utils.sv5T
package_ti.sdo.fc.utils.sv5T,2,copy : package/lib/lib/debug/shmMp/package/package_ti.sdo.fc.utils.sv5T
package_ti.sdo.fc.utils.sv5T,3,copy : package/lib/lib/debug/shmNonMp/package/package_ti.sdo.fc.utils.sv5T
package_ti.sdo.fc.utils.sv5T,4,copy : package/lib/lib/debug/smgr/package/package_ti.sdo.fc.utils.sv5T
package_ti.sdo.fc.utils.sv5T,5,copy : package/lib/lib/debug/smgrmp/package/package_ti.sdo.fc.utils.sv5T
package_ti.sdo.fc.utils.sv5T,6,copy : package/lib/lib/release/rmm/package/package_ti.sdo.fc.utils.sv5T
package_ti.sdo.fc.utils.sv5T,7,copy : package/lib/lib/release/rmmp/package/package_ti.sdo.fc.utils.sv5T
package_ti.sdo.fc.utils.sv5T,8,copy : package/lib/lib/release/shmMp/package/package_ti.sdo.fc.utils.sv5T
package_ti.sdo.fc.utils.sv5T,9,copy : package/lib/lib/release/shmNonMp/package/package_ti.sdo.fc.utils.sv5T
package_ti.sdo.fc.utils.sv5T,10,copy : package/lib/lib/release/smgr/package/package_ti.sdo.fc.utils.sv5T
package_ti.sdo.fc.utils.sv5T,11,copy : package/lib/lib/release/smgrmp/package/package_ti.sdo.fc.utils.sv5T
.PHONY: shmmp.ov5T,copy
shmmp.ov5T,copy : shmmp.ov5T,0,copy shmmp.ov5T,1,copy 
	@

shmmp.ov5T,0,copy : package/lib/lib/debug/shmMp/shmmp.ov5T
shmmp.ov5T,1,copy : package/lib/lib/release/shmMp/shmmp.ov5T
.PHONY: shmmp.sv5T,copy
shmmp.sv5T,copy : shmmp.sv5T,0,copy shmmp.sv5T,1,copy 
	@

shmmp.sv5T,0,copy : package/lib/lib/debug/shmMp/shmmp.sv5T
shmmp.sv5T,1,copy : package/lib/lib/release/shmMp/shmmp.sv5T
.PHONY: rmm.ov5T,copy
rmm.ov5T,copy : rmm.ov5T,0,copy rmm.ov5T,1,copy rmm.ov5T,2,copy rmm.ov5T,3,copy 
	@

rmm.ov5T,0,copy : package/lib/lib/debug/rmm/rmm.ov5T
rmm.ov5T,1,copy : package/lib/lib/debug/rmmp/rmm.ov5T
rmm.ov5T,2,copy : package/lib/lib/release/rmm/rmm.ov5T
rmm.ov5T,3,copy : package/lib/lib/release/rmmp/rmm.ov5T
.PHONY: rmm.sv5T,copy
rmm.sv5T,copy : rmm.sv5T,0,copy rmm.sv5T,1,copy rmm.sv5T,2,copy rmm.sv5T,3,copy 
	@

rmm.sv5T,0,copy : package/lib/lib/debug/rmm/rmm.sv5T
rmm.sv5T,1,copy : package/lib/lib/debug/rmmp/rmm.sv5T
rmm.sv5T,2,copy : package/lib/lib/release/rmm/rmm.sv5T
rmm.sv5T,3,copy : package/lib/lib/release/rmmp/rmm.sv5T
.PHONY: bios_rts.ov5T,copy
bios_rts.ov5T,copy : bios_rts.ov5T,0,copy bios_rts.ov5T,1,copy 
	@

bios_rts.ov5T,0,copy : package/lib/lib/debug/rmm/bios_rts.ov5T
bios_rts.ov5T,1,copy : package/lib/lib/release/rmm/bios_rts.ov5T
.PHONY: bios_rts.sv5T,copy
bios_rts.sv5T,copy : bios_rts.sv5T,0,copy bios_rts.sv5T,1,copy 
	@

bios_rts.sv5T,0,copy : package/lib/lib/debug/rmm/bios_rts.sv5T
bios_rts.sv5T,1,copy : package/lib/lib/release/rmm/bios_rts.sv5T
.PHONY: rmmp.ov5T,copy
rmmp.ov5T,copy : rmmp.ov5T,0,copy rmmp.ov5T,1,copy 
	@

rmmp.ov5T,0,copy : package/lib/lib/debug/rmmp/rmmp.ov5T
rmmp.ov5T,1,copy : package/lib/lib/release/rmmp/rmmp.ov5T
.PHONY: rmmp.sv5T,copy
rmmp.sv5T,copy : rmmp.sv5T,0,copy rmmp.sv5T,1,copy 
	@

rmmp.sv5T,0,copy : package/lib/lib/debug/rmmp/rmmp.sv5T
rmmp.sv5T,1,copy : package/lib/lib/release/rmmp/rmmp.sv5T
.PHONY: smgrmp.ov5T,copy
smgrmp.ov5T,copy : smgrmp.ov5T,0,copy smgrmp.ov5T,1,copy 
	@

smgrmp.ov5T,0,copy : package/lib/lib/debug/smgrmp/smgrmp.ov5T
smgrmp.ov5T,1,copy : package/lib/lib/release/smgrmp/smgrmp.ov5T
.PHONY: smgrmp.sv5T,copy
smgrmp.sv5T,copy : smgrmp.sv5T,0,copy smgrmp.sv5T,1,copy 
	@

smgrmp.sv5T,0,copy : package/lib/lib/debug/smgrmp/smgrmp.sv5T
smgrmp.sv5T,1,copy : package/lib/lib/release/smgrmp/smgrmp.sv5T
.PHONY: smgr.ov5T,copy
smgr.ov5T,copy : smgr.ov5T,0,copy smgr.ov5T,1,copy smgr.ov5T,2,copy smgr.ov5T,3,copy 
	@

smgr.ov5T,0,copy : package/lib/lib/debug/smgr/smgr.ov5T
smgr.ov5T,1,copy : package/lib/lib/debug/smgrmp/smgr.ov5T
smgr.ov5T,2,copy : package/lib/lib/release/smgr/smgr.ov5T
smgr.ov5T,3,copy : package/lib/lib/release/smgrmp/smgr.ov5T
.PHONY: smgr.sv5T,copy
smgr.sv5T,copy : smgr.sv5T,0,copy smgr.sv5T,1,copy smgr.sv5T,2,copy smgr.sv5T,3,copy 
	@

smgr.sv5T,0,copy : package/lib/lib/debug/smgr/smgr.sv5T
smgr.sv5T,1,copy : package/lib/lib/debug/smgrmp/smgr.sv5T
smgr.sv5T,2,copy : package/lib/lib/release/smgr/smgr.sv5T
smgr.sv5T,3,copy : package/lib/lib/release/smgrmp/smgr.sv5T
.PHONY: shm.ov5T,copy
shm.ov5T,copy : shm.ov5T,0,copy shm.ov5T,1,copy 
	@

shm.ov5T,0,copy : package/lib/lib/debug/shmNonMp/shm.ov5T
shm.ov5T,1,copy : package/lib/lib/release/shmNonMp/shm.ov5T
.PHONY: shm.sv5T,copy
shm.sv5T,copy : shm.sv5T,0,copy shm.sv5T,1,copy 
	@

shm.sv5T,0,copy : package/lib/lib/debug/shmNonMp/shm.sv5T
shm.sv5T,1,copy : package/lib/lib/release/shmNonMp/shm.sv5T

$(XDCCFGDIR)%.c $(XDCCFGDIR)%.h $(XDCCFGDIR)%.xdl: $(XDCCFGDIR)%.cfg .interfaces $(XDCROOT)/packages/xdc/cfg/Main.xs
	@$(MSG) "configuring $(_PROG_NAME) from $< ..."
	$(CONFIG) $(_PROG_XSOPTS) xdc.cfg $(_PROG_NAME) $(XDCCFGDIR)$*.cfg $(XDCCFGDIR)$*

.PHONY: release,ti_sdo_fc_utils
ti_sdo_fc_utils.tar: package/package.bld.xml
ti_sdo_fc_utils.tar: package/package.ext.xml
ti_sdo_fc_utils.tar: package/package.rel.dot
ti_sdo_fc_utils.tar: package/build.cfg
ti_sdo_fc_utils.tar: package/package.xdc.inc
ti_sdo_fc_utils.tar: shm.h
ti_sdo_fc_utils.tar: _rmm.h
ti_sdo_fc_utils.tar: _smgr.h
ti_sdo_fc_utils.tar: dbc.h
ti_sdo_fc_utils.tar: rmm.h
ti_sdo_fc_utils.tar: smgr.h
ti_sdo_fc_utils.tar: lock.h
ti_sdo_fc_utils.tar: utils.xs
ti_sdo_fc_utils.tar: rmmp.h
ti_sdo_fc_utils.tar: smgrmp.h
ti_sdo_fc_utils.tar: package.bld
ti_sdo_fc_utils.tar: bios_rts.h
ti_sdo_fc_utils.tar: memleakcheck.h
ti_sdo_fc_utils.tar: _rmmScratch.h
ti_sdo_fc_utils.tar: _rmmp.h
ti_sdo_fc_utils.tar: _smgrmp.h
ti_sdo_fc_utils.tar: simple_GCArmv5T.mak
ti_sdo_fc_utils.tar: package/package.cfg.xdc.inc
ti_sdo_fc_utils.tar: lib/debug/rmm.aem3
ti_sdo_fc_utils.tar: package/package_ti.sdo.fc.utils.c
ti_sdo_fc_utils.tar: rmm.c
ti_sdo_fc_utils.tar: lib/release/rmm.aem3
ti_sdo_fc_utils.tar: lib/debug/smgr.aem3
ti_sdo_fc_utils.tar: smgr.c
ti_sdo_fc_utils.tar: lib/release/smgr.aem3
ti_sdo_fc_utils.tar: lib/debug/rmmp.aem3
ti_sdo_fc_utils.tar: rmmp.c
ti_sdo_fc_utils.tar: lib/release/rmmp.aem3
ti_sdo_fc_utils.tar: lib/debug/rmm.ae674
ti_sdo_fc_utils.tar: lib/release/rmm.ae674
ti_sdo_fc_utils.tar: lib/debug/smgr.ae674
ti_sdo_fc_utils.tar: lib/release/smgr.ae674
ti_sdo_fc_utils.tar: lib/debug/rmmp.ae674
ti_sdo_fc_utils.tar: lib/release/rmmp.ae674
ti_sdo_fc_utils.tar: lib/debug/shmMp.av5T
ti_sdo_fc_utils.tar: shmmp.c
ti_sdo_fc_utils.tar: lib/release/shmMp.av5T
ti_sdo_fc_utils.tar: lib/debug/rmm.av5T
ti_sdo_fc_utils.tar: bios_rts.c
ti_sdo_fc_utils.tar: lib/release/rmm.av5T
ti_sdo_fc_utils.tar: lib/debug/rmmp.av5T
ti_sdo_fc_utils.tar: lib/release/rmmp.av5T
ti_sdo_fc_utils.tar: lib/debug/smgrmp.av5T
ti_sdo_fc_utils.tar: smgrmp.c
ti_sdo_fc_utils.tar: lib/release/smgrmp.av5T
ti_sdo_fc_utils.tar: lib/debug/smgr.av5T
ti_sdo_fc_utils.tar: lib/release/smgr.av5T
ti_sdo_fc_utils.tar: lib/debug/shmNonMp.av5T
ti_sdo_fc_utils.tar: shm.c
ti_sdo_fc_utils.tar: lib/release/shmNonMp.av5T
ifeq (,$(MK_NOGENDEPS))
-include package/rel/ti_sdo_fc_utils.tar.dep
endif
package/rel/ti_sdo_fc_utils/ti/sdo/fc/utils/package/package.rel.xml:

ti_sdo_fc_utils.tar: package/rel/ti_sdo_fc_utils.xdc.inc package/rel/ti_sdo_fc_utils/ti/sdo/fc/utils/package/package.rel.xml
	@$(MSG) making release file $@ "(because of $(firstword $?))" ...
	-$(RM) $@
	$(call MKRELTAR,package/rel/ti_sdo_fc_utils.xdc.inc,package/rel/ti_sdo_fc_utils.tar.dep)


release release,ti_sdo_fc_utils: all ti_sdo_fc_utils.tar
clean:: .clean
	-$(RM) ti_sdo_fc_utils.tar
	-$(RM) package/rel/ti_sdo_fc_utils.xdc.inc
	-$(RM) package/rel/ti_sdo_fc_utils.tar.dep

clean:: .clean
	-$(RM) .libraries .libraries,*
clean:: 
	-$(RM) .dlls .dlls,*
#
# The following clean rule removes user specified
# generated files or directories.
#
	-$(RMDIR) lib/

ifneq (clean,$(MAKECMDGOALS))
ifeq (,$(wildcard lib))
    $(shell $(MKDIR) lib)
endif
ifeq (,$(wildcard lib/debug))
    $(shell $(MKDIR) lib/debug)
endif
ifeq (,$(wildcard lib/release))
    $(shell $(MKDIR) lib/release)
endif
ifeq (,$(wildcard package))
    $(shell $(MKDIR) package)
endif
ifeq (,$(wildcard package/cfg))
    $(shell $(MKDIR) package/cfg)
endif
ifeq (,$(wildcard package/lib))
    $(shell $(MKDIR) package/lib)
endif
ifeq (,$(wildcard package/rel))
    $(shell $(MKDIR) package/rel)
endif
ifeq (,$(wildcard package/internal))
    $(shell $(MKDIR) package/internal)
endif
ifeq (,$(wildcard package/external))
    $(shell $(MKDIR) package/external)
endif
ifeq (,$(wildcard package/lib/lib))
    $(shell $(MKDIR) package/lib/lib)
endif
ifeq (,$(wildcard package/lib/lib/debug))
    $(shell $(MKDIR) package/lib/lib/debug)
endif
ifeq (,$(wildcard package/lib/lib/debug/rmm))
    $(shell $(MKDIR) package/lib/lib/debug/rmm)
endif
ifeq (,$(wildcard package/lib/lib/debug/rmm/package))
    $(shell $(MKDIR) package/lib/lib/debug/rmm/package)
endif
ifeq (,$(wildcard package/lib/lib/release))
    $(shell $(MKDIR) package/lib/lib/release)
endif
ifeq (,$(wildcard package/lib/lib/release/rmm))
    $(shell $(MKDIR) package/lib/lib/release/rmm)
endif
ifeq (,$(wildcard package/lib/lib/release/rmm/package))
    $(shell $(MKDIR) package/lib/lib/release/rmm/package)
endif
ifeq (,$(wildcard package/lib/lib/debug/smgr))
    $(shell $(MKDIR) package/lib/lib/debug/smgr)
endif
ifeq (,$(wildcard package/lib/lib/debug/smgr/package))
    $(shell $(MKDIR) package/lib/lib/debug/smgr/package)
endif
ifeq (,$(wildcard package/lib/lib/release/smgr))
    $(shell $(MKDIR) package/lib/lib/release/smgr)
endif
ifeq (,$(wildcard package/lib/lib/release/smgr/package))
    $(shell $(MKDIR) package/lib/lib/release/smgr/package)
endif
ifeq (,$(wildcard package/lib/lib/debug/rmmp))
    $(shell $(MKDIR) package/lib/lib/debug/rmmp)
endif
ifeq (,$(wildcard package/lib/lib/debug/rmmp/package))
    $(shell $(MKDIR) package/lib/lib/debug/rmmp/package)
endif
ifeq (,$(wildcard package/lib/lib/release/rmmp))
    $(shell $(MKDIR) package/lib/lib/release/rmmp)
endif
ifeq (,$(wildcard package/lib/lib/release/rmmp/package))
    $(shell $(MKDIR) package/lib/lib/release/rmmp/package)
endif
ifeq (,$(wildcard package/lib/lib/debug/shmMp))
    $(shell $(MKDIR) package/lib/lib/debug/shmMp)
endif
ifeq (,$(wildcard package/lib/lib/debug/shmMp/package))
    $(shell $(MKDIR) package/lib/lib/debug/shmMp/package)
endif
ifeq (,$(wildcard package/lib/lib/release/shmMp))
    $(shell $(MKDIR) package/lib/lib/release/shmMp)
endif
ifeq (,$(wildcard package/lib/lib/release/shmMp/package))
    $(shell $(MKDIR) package/lib/lib/release/shmMp/package)
endif
ifeq (,$(wildcard package/lib/lib/debug/smgrmp))
    $(shell $(MKDIR) package/lib/lib/debug/smgrmp)
endif
ifeq (,$(wildcard package/lib/lib/debug/smgrmp/package))
    $(shell $(MKDIR) package/lib/lib/debug/smgrmp/package)
endif
ifeq (,$(wildcard package/lib/lib/release/smgrmp))
    $(shell $(MKDIR) package/lib/lib/release/smgrmp)
endif
ifeq (,$(wildcard package/lib/lib/release/smgrmp/package))
    $(shell $(MKDIR) package/lib/lib/release/smgrmp/package)
endif
ifeq (,$(wildcard package/lib/lib/debug/shmNonMp))
    $(shell $(MKDIR) package/lib/lib/debug/shmNonMp)
endif
ifeq (,$(wildcard package/lib/lib/debug/shmNonMp/package))
    $(shell $(MKDIR) package/lib/lib/debug/shmNonMp/package)
endif
ifeq (,$(wildcard package/lib/lib/release/shmNonMp))
    $(shell $(MKDIR) package/lib/lib/release/shmNonMp)
endif
ifeq (,$(wildcard package/lib/lib/release/shmNonMp/package))
    $(shell $(MKDIR) package/lib/lib/release/shmNonMp/package)
endif
endif
clean::
	-$(RMDIR) package


clean:: 
	-$(RM) package/ti.sdo.fc.utils.pjt
