#
#  Do not edit this file.  This file is generated from 
#  package.bld.  Any modifications to this file will be 
#  overwritten whenever makefiles are re-generated.
#
#  target compatibility key = gnu.targets.arm.GCArmv5T{1,0,4.3,3
#
ifeq (,$(MK_NOGENDEPS))
-include package/lib/release/opencl_api_syslink/package/package_ti.sdo.opencl.ov5T.dep
endif

package/lib/release/opencl_api_syslink/package/package_ti.sdo.opencl.ov5T: | .interfaces
package/lib/release/opencl_api_syslink/package/package_ti.sdo.opencl.ov5T: package/package_ti.sdo.opencl.c lib/release/opencl_api_syslink.av5T.mak
	@$(RM) $@.dep
	$(RM) $@
	@$(MSG) clv5T $< ...
	$(gnu.targets.arm.GCArmv5T.rootDir)/bin/arm-none-linux-gnueabi-gcc -c -MD -MF $@.dep -x c  -fPIC -Wunused -march=armv5t -Dfar=  -Wall -fno-strict-aliasing  -DOpenCL_ti_syslink -Dxdc_target_name__=GCArmv5T -Dxdc_target_types__=gnu/targets/arm/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_4_3_3 -O2 -ffunction-sections -fdata-sections -I/swcoe/sdk/cm/netra/ti-ezsdk_dm816x-evm_5_05_01_04/component-sources/framework_components_3_22_01_07/packages/khronos/opencl/  $(XDCINCS)  -o $@ $<
	-@$(FIXDEP) $@.dep $@.dep
	
package/lib/release/opencl_api_syslink/package/package_ti.sdo.opencl.ov5T: export LD_LIBRARY_PATH=

package/lib/release/opencl_api_syslink/package/package_ti.sdo.opencl.sv5T: | .interfaces
package/lib/release/opencl_api_syslink/package/package_ti.sdo.opencl.sv5T: package/package_ti.sdo.opencl.c lib/release/opencl_api_syslink.av5T.mak
	@$(RM) $@.dep
	$(RM) $@
	@$(MSG) clv5T -S $< ...
	$(gnu.targets.arm.GCArmv5T.rootDir)/bin/arm-none-linux-gnueabi-gcc -c -MD -MF $@.dep -x c -S -fPIC -Wunused -march=armv5t -Dfar=  -Wall -fno-strict-aliasing  -DOpenCL_ti_syslink -Dxdc_target_name__=GCArmv5T -Dxdc_target_types__=gnu/targets/arm/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_4_3_3 -O2 -ffunction-sections -fdata-sections -I/swcoe/sdk/cm/netra/ti-ezsdk_dm816x-evm_5_05_01_04/component-sources/framework_components_3_22_01_07/packages/khronos/opencl/  $(XDCINCS)  -o $@ $<
	-@$(FIXDEP) $@.dep $@.dep
	
package/lib/release/opencl_api_syslink/package/package_ti.sdo.opencl.sv5T: export LD_LIBRARY_PATH=

ifeq (,$(MK_NOGENDEPS))
-include package/lib/release/opencl_api_syslink/CLCommandQueue.ov5T.dep
endif

package/lib/release/opencl_api_syslink/CLCommandQueue.ov5T: | .interfaces
package/lib/release/opencl_api_syslink/CLCommandQueue.ov5T: CLCommandQueue.c lib/release/opencl_api_syslink.av5T.mak
	@$(RM) $@.dep
	$(RM) $@
	@$(MSG) clv5T $< ...
	$(gnu.targets.arm.GCArmv5T.rootDir)/bin/arm-none-linux-gnueabi-gcc -c -MD -MF $@.dep -x c  -fPIC -Wunused -march=armv5t -Dfar=  -Wall -fno-strict-aliasing  -DOpenCL_ti_syslink -Dxdc_target_name__=GCArmv5T -Dxdc_target_types__=gnu/targets/arm/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_4_3_3 -O2 -ffunction-sections -fdata-sections -I/swcoe/sdk/cm/netra/ti-ezsdk_dm816x-evm_5_05_01_04/component-sources/framework_components_3_22_01_07/packages/khronos/opencl/  $(XDCINCS)  -o $@ $<
	-@$(FIXDEP) $@.dep $@.dep
	
package/lib/release/opencl_api_syslink/CLCommandQueue.ov5T: export LD_LIBRARY_PATH=

package/lib/release/opencl_api_syslink/CLCommandQueue.sv5T: | .interfaces
package/lib/release/opencl_api_syslink/CLCommandQueue.sv5T: CLCommandQueue.c lib/release/opencl_api_syslink.av5T.mak
	@$(RM) $@.dep
	$(RM) $@
	@$(MSG) clv5T -S $< ...
	$(gnu.targets.arm.GCArmv5T.rootDir)/bin/arm-none-linux-gnueabi-gcc -c -MD -MF $@.dep -x c -S -fPIC -Wunused -march=armv5t -Dfar=  -Wall -fno-strict-aliasing  -DOpenCL_ti_syslink -Dxdc_target_name__=GCArmv5T -Dxdc_target_types__=gnu/targets/arm/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_4_3_3 -O2 -ffunction-sections -fdata-sections -I/swcoe/sdk/cm/netra/ti-ezsdk_dm816x-evm_5_05_01_04/component-sources/framework_components_3_22_01_07/packages/khronos/opencl/  $(XDCINCS)  -o $@ $<
	-@$(FIXDEP) $@.dep $@.dep
	
package/lib/release/opencl_api_syslink/CLCommandQueue.sv5T: export LD_LIBRARY_PATH=

ifeq (,$(MK_NOGENDEPS))
-include package/lib/release/opencl_api_syslink/CLContext.ov5T.dep
endif

package/lib/release/opencl_api_syslink/CLContext.ov5T: | .interfaces
package/lib/release/opencl_api_syslink/CLContext.ov5T: CLContext.c lib/release/opencl_api_syslink.av5T.mak
	@$(RM) $@.dep
	$(RM) $@
	@$(MSG) clv5T $< ...
	$(gnu.targets.arm.GCArmv5T.rootDir)/bin/arm-none-linux-gnueabi-gcc -c -MD -MF $@.dep -x c  -fPIC -Wunused -march=armv5t -Dfar=  -Wall -fno-strict-aliasing  -DOpenCL_ti_syslink -Dxdc_target_name__=GCArmv5T -Dxdc_target_types__=gnu/targets/arm/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_4_3_3 -O2 -ffunction-sections -fdata-sections -I/swcoe/sdk/cm/netra/ti-ezsdk_dm816x-evm_5_05_01_04/component-sources/framework_components_3_22_01_07/packages/khronos/opencl/  $(XDCINCS)  -o $@ $<
	-@$(FIXDEP) $@.dep $@.dep
	
package/lib/release/opencl_api_syslink/CLContext.ov5T: export LD_LIBRARY_PATH=

package/lib/release/opencl_api_syslink/CLContext.sv5T: | .interfaces
package/lib/release/opencl_api_syslink/CLContext.sv5T: CLContext.c lib/release/opencl_api_syslink.av5T.mak
	@$(RM) $@.dep
	$(RM) $@
	@$(MSG) clv5T -S $< ...
	$(gnu.targets.arm.GCArmv5T.rootDir)/bin/arm-none-linux-gnueabi-gcc -c -MD -MF $@.dep -x c -S -fPIC -Wunused -march=armv5t -Dfar=  -Wall -fno-strict-aliasing  -DOpenCL_ti_syslink -Dxdc_target_name__=GCArmv5T -Dxdc_target_types__=gnu/targets/arm/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_4_3_3 -O2 -ffunction-sections -fdata-sections -I/swcoe/sdk/cm/netra/ti-ezsdk_dm816x-evm_5_05_01_04/component-sources/framework_components_3_22_01_07/packages/khronos/opencl/  $(XDCINCS)  -o $@ $<
	-@$(FIXDEP) $@.dep $@.dep
	
package/lib/release/opencl_api_syslink/CLContext.sv5T: export LD_LIBRARY_PATH=

ifeq (,$(MK_NOGENDEPS))
-include package/lib/release/opencl_api_syslink/CLDevice.ov5T.dep
endif

package/lib/release/opencl_api_syslink/CLDevice.ov5T: | .interfaces
package/lib/release/opencl_api_syslink/CLDevice.ov5T: CLDevice.c lib/release/opencl_api_syslink.av5T.mak
	@$(RM) $@.dep
	$(RM) $@
	@$(MSG) clv5T $< ...
	$(gnu.targets.arm.GCArmv5T.rootDir)/bin/arm-none-linux-gnueabi-gcc -c -MD -MF $@.dep -x c  -fPIC -Wunused -march=armv5t -Dfar=  -Wall -fno-strict-aliasing  -DOpenCL_ti_syslink -Dxdc_target_name__=GCArmv5T -Dxdc_target_types__=gnu/targets/arm/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_4_3_3 -O2 -ffunction-sections -fdata-sections -I/swcoe/sdk/cm/netra/ti-ezsdk_dm816x-evm_5_05_01_04/component-sources/framework_components_3_22_01_07/packages/khronos/opencl/  $(XDCINCS)  -o $@ $<
	-@$(FIXDEP) $@.dep $@.dep
	
package/lib/release/opencl_api_syslink/CLDevice.ov5T: export LD_LIBRARY_PATH=

package/lib/release/opencl_api_syslink/CLDevice.sv5T: | .interfaces
package/lib/release/opencl_api_syslink/CLDevice.sv5T: CLDevice.c lib/release/opencl_api_syslink.av5T.mak
	@$(RM) $@.dep
	$(RM) $@
	@$(MSG) clv5T -S $< ...
	$(gnu.targets.arm.GCArmv5T.rootDir)/bin/arm-none-linux-gnueabi-gcc -c -MD -MF $@.dep -x c -S -fPIC -Wunused -march=armv5t -Dfar=  -Wall -fno-strict-aliasing  -DOpenCL_ti_syslink -Dxdc_target_name__=GCArmv5T -Dxdc_target_types__=gnu/targets/arm/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_4_3_3 -O2 -ffunction-sections -fdata-sections -I/swcoe/sdk/cm/netra/ti-ezsdk_dm816x-evm_5_05_01_04/component-sources/framework_components_3_22_01_07/packages/khronos/opencl/  $(XDCINCS)  -o $@ $<
	-@$(FIXDEP) $@.dep $@.dep
	
package/lib/release/opencl_api_syslink/CLDevice.sv5T: export LD_LIBRARY_PATH=

ifeq (,$(MK_NOGENDEPS))
-include package/lib/release/opencl_api_syslink/CLPlatform.ov5T.dep
endif

package/lib/release/opencl_api_syslink/CLPlatform.ov5T: | .interfaces
package/lib/release/opencl_api_syslink/CLPlatform.ov5T: CLPlatform.c lib/release/opencl_api_syslink.av5T.mak
	@$(RM) $@.dep
	$(RM) $@
	@$(MSG) clv5T $< ...
	$(gnu.targets.arm.GCArmv5T.rootDir)/bin/arm-none-linux-gnueabi-gcc -c -MD -MF $@.dep -x c  -fPIC -Wunused -march=armv5t -Dfar=  -Wall -fno-strict-aliasing  -DOpenCL_ti_syslink -Dxdc_target_name__=GCArmv5T -Dxdc_target_types__=gnu/targets/arm/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_4_3_3 -O2 -ffunction-sections -fdata-sections -I/swcoe/sdk/cm/netra/ti-ezsdk_dm816x-evm_5_05_01_04/component-sources/framework_components_3_22_01_07/packages/khronos/opencl/  $(XDCINCS)  -o $@ $<
	-@$(FIXDEP) $@.dep $@.dep
	
package/lib/release/opencl_api_syslink/CLPlatform.ov5T: export LD_LIBRARY_PATH=

package/lib/release/opencl_api_syslink/CLPlatform.sv5T: | .interfaces
package/lib/release/opencl_api_syslink/CLPlatform.sv5T: CLPlatform.c lib/release/opencl_api_syslink.av5T.mak
	@$(RM) $@.dep
	$(RM) $@
	@$(MSG) clv5T -S $< ...
	$(gnu.targets.arm.GCArmv5T.rootDir)/bin/arm-none-linux-gnueabi-gcc -c -MD -MF $@.dep -x c -S -fPIC -Wunused -march=armv5t -Dfar=  -Wall -fno-strict-aliasing  -DOpenCL_ti_syslink -Dxdc_target_name__=GCArmv5T -Dxdc_target_types__=gnu/targets/arm/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_4_3_3 -O2 -ffunction-sections -fdata-sections -I/swcoe/sdk/cm/netra/ti-ezsdk_dm816x-evm_5_05_01_04/component-sources/framework_components_3_22_01_07/packages/khronos/opencl/  $(XDCINCS)  -o $@ $<
	-@$(FIXDEP) $@.dep $@.dep
	
package/lib/release/opencl_api_syslink/CLPlatform.sv5T: export LD_LIBRARY_PATH=

ifeq (,$(MK_NOGENDEPS))
-include package/lib/release/opencl_api_syslink/CLProgram.ov5T.dep
endif

package/lib/release/opencl_api_syslink/CLProgram.ov5T: | .interfaces
package/lib/release/opencl_api_syslink/CLProgram.ov5T: CLProgram.c lib/release/opencl_api_syslink.av5T.mak
	@$(RM) $@.dep
	$(RM) $@
	@$(MSG) clv5T $< ...
	$(gnu.targets.arm.GCArmv5T.rootDir)/bin/arm-none-linux-gnueabi-gcc -c -MD -MF $@.dep -x c  -fPIC -Wunused -march=armv5t -Dfar=  -Wall -fno-strict-aliasing  -DOpenCL_ti_syslink -Dxdc_target_name__=GCArmv5T -Dxdc_target_types__=gnu/targets/arm/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_4_3_3 -O2 -ffunction-sections -fdata-sections -I/swcoe/sdk/cm/netra/ti-ezsdk_dm816x-evm_5_05_01_04/component-sources/framework_components_3_22_01_07/packages/khronos/opencl/  $(XDCINCS)  -o $@ $<
	-@$(FIXDEP) $@.dep $@.dep
	
package/lib/release/opencl_api_syslink/CLProgram.ov5T: export LD_LIBRARY_PATH=

package/lib/release/opencl_api_syslink/CLProgram.sv5T: | .interfaces
package/lib/release/opencl_api_syslink/CLProgram.sv5T: CLProgram.c lib/release/opencl_api_syslink.av5T.mak
	@$(RM) $@.dep
	$(RM) $@
	@$(MSG) clv5T -S $< ...
	$(gnu.targets.arm.GCArmv5T.rootDir)/bin/arm-none-linux-gnueabi-gcc -c -MD -MF $@.dep -x c -S -fPIC -Wunused -march=armv5t -Dfar=  -Wall -fno-strict-aliasing  -DOpenCL_ti_syslink -Dxdc_target_name__=GCArmv5T -Dxdc_target_types__=gnu/targets/arm/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_4_3_3 -O2 -ffunction-sections -fdata-sections -I/swcoe/sdk/cm/netra/ti-ezsdk_dm816x-evm_5_05_01_04/component-sources/framework_components_3_22_01_07/packages/khronos/opencl/  $(XDCINCS)  -o $@ $<
	-@$(FIXDEP) $@.dep $@.dep
	
package/lib/release/opencl_api_syslink/CLProgram.sv5T: export LD_LIBRARY_PATH=

ifeq (,$(MK_NOGENDEPS))
-include package/lib/release/opencl_api_syslink/CLMemObj.ov5T.dep
endif

package/lib/release/opencl_api_syslink/CLMemObj.ov5T: | .interfaces
package/lib/release/opencl_api_syslink/CLMemObj.ov5T: CLMemObj.c lib/release/opencl_api_syslink.av5T.mak
	@$(RM) $@.dep
	$(RM) $@
	@$(MSG) clv5T $< ...
	$(gnu.targets.arm.GCArmv5T.rootDir)/bin/arm-none-linux-gnueabi-gcc -c -MD -MF $@.dep -x c  -fPIC -Wunused -march=armv5t -Dfar=  -Wall -fno-strict-aliasing  -DOpenCL_ti_syslink -Dxdc_target_name__=GCArmv5T -Dxdc_target_types__=gnu/targets/arm/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_4_3_3 -O2 -ffunction-sections -fdata-sections -I/swcoe/sdk/cm/netra/ti-ezsdk_dm816x-evm_5_05_01_04/component-sources/framework_components_3_22_01_07/packages/khronos/opencl/  $(XDCINCS)  -o $@ $<
	-@$(FIXDEP) $@.dep $@.dep
	
package/lib/release/opencl_api_syslink/CLMemObj.ov5T: export LD_LIBRARY_PATH=

package/lib/release/opencl_api_syslink/CLMemObj.sv5T: | .interfaces
package/lib/release/opencl_api_syslink/CLMemObj.sv5T: CLMemObj.c lib/release/opencl_api_syslink.av5T.mak
	@$(RM) $@.dep
	$(RM) $@
	@$(MSG) clv5T -S $< ...
	$(gnu.targets.arm.GCArmv5T.rootDir)/bin/arm-none-linux-gnueabi-gcc -c -MD -MF $@.dep -x c -S -fPIC -Wunused -march=armv5t -Dfar=  -Wall -fno-strict-aliasing  -DOpenCL_ti_syslink -Dxdc_target_name__=GCArmv5T -Dxdc_target_types__=gnu/targets/arm/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_4_3_3 -O2 -ffunction-sections -fdata-sections -I/swcoe/sdk/cm/netra/ti-ezsdk_dm816x-evm_5_05_01_04/component-sources/framework_components_3_22_01_07/packages/khronos/opencl/  $(XDCINCS)  -o $@ $<
	-@$(FIXDEP) $@.dep $@.dep
	
package/lib/release/opencl_api_syslink/CLMemObj.sv5T: export LD_LIBRARY_PATH=

ifeq (,$(MK_NOGENDEPS))
-include package/lib/release/opencl_api_syslink/CLKernel.ov5T.dep
endif

package/lib/release/opencl_api_syslink/CLKernel.ov5T: | .interfaces
package/lib/release/opencl_api_syslink/CLKernel.ov5T: CLKernel.c lib/release/opencl_api_syslink.av5T.mak
	@$(RM) $@.dep
	$(RM) $@
	@$(MSG) clv5T $< ...
	$(gnu.targets.arm.GCArmv5T.rootDir)/bin/arm-none-linux-gnueabi-gcc -c -MD -MF $@.dep -x c  -fPIC -Wunused -march=armv5t -Dfar=  -Wall -fno-strict-aliasing  -DOpenCL_ti_syslink -Dxdc_target_name__=GCArmv5T -Dxdc_target_types__=gnu/targets/arm/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_4_3_3 -O2 -ffunction-sections -fdata-sections -I/swcoe/sdk/cm/netra/ti-ezsdk_dm816x-evm_5_05_01_04/component-sources/framework_components_3_22_01_07/packages/khronos/opencl/  $(XDCINCS)  -o $@ $<
	-@$(FIXDEP) $@.dep $@.dep
	
package/lib/release/opencl_api_syslink/CLKernel.ov5T: export LD_LIBRARY_PATH=

package/lib/release/opencl_api_syslink/CLKernel.sv5T: | .interfaces
package/lib/release/opencl_api_syslink/CLKernel.sv5T: CLKernel.c lib/release/opencl_api_syslink.av5T.mak
	@$(RM) $@.dep
	$(RM) $@
	@$(MSG) clv5T -S $< ...
	$(gnu.targets.arm.GCArmv5T.rootDir)/bin/arm-none-linux-gnueabi-gcc -c -MD -MF $@.dep -x c -S -fPIC -Wunused -march=armv5t -Dfar=  -Wall -fno-strict-aliasing  -DOpenCL_ti_syslink -Dxdc_target_name__=GCArmv5T -Dxdc_target_types__=gnu/targets/arm/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_4_3_3 -O2 -ffunction-sections -fdata-sections -I/swcoe/sdk/cm/netra/ti-ezsdk_dm816x-evm_5_05_01_04/component-sources/framework_components_3_22_01_07/packages/khronos/opencl/  $(XDCINCS)  -o $@ $<
	-@$(FIXDEP) $@.dep $@.dep
	
package/lib/release/opencl_api_syslink/CLKernel.sv5T: export LD_LIBRARY_PATH=

ifeq (,$(MK_NOGENDEPS))
-include package/lib/release/opencl_api_syslink/CLEvent.ov5T.dep
endif

package/lib/release/opencl_api_syslink/CLEvent.ov5T: | .interfaces
package/lib/release/opencl_api_syslink/CLEvent.ov5T: CLEvent.c lib/release/opencl_api_syslink.av5T.mak
	@$(RM) $@.dep
	$(RM) $@
	@$(MSG) clv5T $< ...
	$(gnu.targets.arm.GCArmv5T.rootDir)/bin/arm-none-linux-gnueabi-gcc -c -MD -MF $@.dep -x c  -fPIC -Wunused -march=armv5t -Dfar=  -Wall -fno-strict-aliasing  -DOpenCL_ti_syslink -Dxdc_target_name__=GCArmv5T -Dxdc_target_types__=gnu/targets/arm/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_4_3_3 -O2 -ffunction-sections -fdata-sections -I/swcoe/sdk/cm/netra/ti-ezsdk_dm816x-evm_5_05_01_04/component-sources/framework_components_3_22_01_07/packages/khronos/opencl/  $(XDCINCS)  -o $@ $<
	-@$(FIXDEP) $@.dep $@.dep
	
package/lib/release/opencl_api_syslink/CLEvent.ov5T: export LD_LIBRARY_PATH=

package/lib/release/opencl_api_syslink/CLEvent.sv5T: | .interfaces
package/lib/release/opencl_api_syslink/CLEvent.sv5T: CLEvent.c lib/release/opencl_api_syslink.av5T.mak
	@$(RM) $@.dep
	$(RM) $@
	@$(MSG) clv5T -S $< ...
	$(gnu.targets.arm.GCArmv5T.rootDir)/bin/arm-none-linux-gnueabi-gcc -c -MD -MF $@.dep -x c -S -fPIC -Wunused -march=armv5t -Dfar=  -Wall -fno-strict-aliasing  -DOpenCL_ti_syslink -Dxdc_target_name__=GCArmv5T -Dxdc_target_types__=gnu/targets/arm/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_4_3_3 -O2 -ffunction-sections -fdata-sections -I/swcoe/sdk/cm/netra/ti-ezsdk_dm816x-evm_5_05_01_04/component-sources/framework_components_3_22_01_07/packages/khronos/opencl/  $(XDCINCS)  -o $@ $<
	-@$(FIXDEP) $@.dep $@.dep
	
package/lib/release/opencl_api_syslink/CLEvent.sv5T: export LD_LIBRARY_PATH=

ifeq (,$(MK_NOGENDEPS))
-include package/lib/release/opencl_api_syslink/CLMemObj_syslink.ov5T.dep
endif

package/lib/release/opencl_api_syslink/CLMemObj_syslink.ov5T: | .interfaces
package/lib/release/opencl_api_syslink/CLMemObj_syslink.ov5T: CLMemObj_syslink.c lib/release/opencl_api_syslink.av5T.mak
	@$(RM) $@.dep
	$(RM) $@
	@$(MSG) clv5T $< ...
	$(gnu.targets.arm.GCArmv5T.rootDir)/bin/arm-none-linux-gnueabi-gcc -c -MD -MF $@.dep -x c  -fPIC -Wunused -march=armv5t -Dfar=  -Wall -fno-strict-aliasing  -DOpenCL_ti_syslink -Dxdc_target_name__=GCArmv5T -Dxdc_target_types__=gnu/targets/arm/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_4_3_3 -O2 -ffunction-sections -fdata-sections -I/swcoe/sdk/cm/netra/ti-ezsdk_dm816x-evm_5_05_01_04/component-sources/framework_components_3_22_01_07/packages/khronos/opencl/  $(XDCINCS)  -o $@ $<
	-@$(FIXDEP) $@.dep $@.dep
	
package/lib/release/opencl_api_syslink/CLMemObj_syslink.ov5T: export LD_LIBRARY_PATH=

package/lib/release/opencl_api_syslink/CLMemObj_syslink.sv5T: | .interfaces
package/lib/release/opencl_api_syslink/CLMemObj_syslink.sv5T: CLMemObj_syslink.c lib/release/opencl_api_syslink.av5T.mak
	@$(RM) $@.dep
	$(RM) $@
	@$(MSG) clv5T -S $< ...
	$(gnu.targets.arm.GCArmv5T.rootDir)/bin/arm-none-linux-gnueabi-gcc -c -MD -MF $@.dep -x c -S -fPIC -Wunused -march=armv5t -Dfar=  -Wall -fno-strict-aliasing  -DOpenCL_ti_syslink -Dxdc_target_name__=GCArmv5T -Dxdc_target_types__=gnu/targets/arm/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_4_3_3 -O2 -ffunction-sections -fdata-sections -I/swcoe/sdk/cm/netra/ti-ezsdk_dm816x-evm_5_05_01_04/component-sources/framework_components_3_22_01_07/packages/khronos/opencl/  $(XDCINCS)  -o $@ $<
	-@$(FIXDEP) $@.dep $@.dep
	
package/lib/release/opencl_api_syslink/CLMemObj_syslink.sv5T: export LD_LIBRARY_PATH=

clean,v5T ::
	-$(RM) package/lib/release/opencl_api_syslink/package/package_ti.sdo.opencl.ov5T
	-$(RM) package/lib/release/opencl_api_syslink/CLCommandQueue.ov5T
	-$(RM) package/lib/release/opencl_api_syslink/CLContext.ov5T
	-$(RM) package/lib/release/opencl_api_syslink/CLDevice.ov5T
	-$(RM) package/lib/release/opencl_api_syslink/CLPlatform.ov5T
	-$(RM) package/lib/release/opencl_api_syslink/CLProgram.ov5T
	-$(RM) package/lib/release/opencl_api_syslink/CLMemObj.ov5T
	-$(RM) package/lib/release/opencl_api_syslink/CLKernel.ov5T
	-$(RM) package/lib/release/opencl_api_syslink/CLEvent.ov5T
	-$(RM) package/lib/release/opencl_api_syslink/CLMemObj_syslink.ov5T
	-$(RM) package/lib/release/opencl_api_syslink/package/package_ti.sdo.opencl.sv5T
	-$(RM) package/lib/release/opencl_api_syslink/CLCommandQueue.sv5T
	-$(RM) package/lib/release/opencl_api_syslink/CLContext.sv5T
	-$(RM) package/lib/release/opencl_api_syslink/CLDevice.sv5T
	-$(RM) package/lib/release/opencl_api_syslink/CLPlatform.sv5T
	-$(RM) package/lib/release/opencl_api_syslink/CLProgram.sv5T
	-$(RM) package/lib/release/opencl_api_syslink/CLMemObj.sv5T
	-$(RM) package/lib/release/opencl_api_syslink/CLKernel.sv5T
	-$(RM) package/lib/release/opencl_api_syslink/CLEvent.sv5T
	-$(RM) package/lib/release/opencl_api_syslink/CLMemObj_syslink.sv5T

lib/release/opencl_api_syslink.av5T: package/lib/release/opencl_api_syslink/package/package_ti.sdo.opencl.ov5T package/lib/release/opencl_api_syslink/CLCommandQueue.ov5T package/lib/release/opencl_api_syslink/CLContext.ov5T package/lib/release/opencl_api_syslink/CLDevice.ov5T package/lib/release/opencl_api_syslink/CLPlatform.ov5T package/lib/release/opencl_api_syslink/CLProgram.ov5T package/lib/release/opencl_api_syslink/CLMemObj.ov5T package/lib/release/opencl_api_syslink/CLKernel.ov5T package/lib/release/opencl_api_syslink/CLEvent.ov5T package/lib/release/opencl_api_syslink/CLMemObj_syslink.ov5T lib/release/opencl_api_syslink.av5T.mak

clean::
	-$(RM) lib/release/opencl_api_syslink.av5T.mak
